-- Hatcher AT formalization. Target modules are generated by /autoform:setup + /autoform:orchestrate.
import Hatcher.Circle.Covering
import Hatcher.Circle.WindingNumber
import Hatcher.Circle.FundamentalGroup
import Hatcher.Disc.NoRetraction
