/-
Copyright (c) 2026 Jack McCarthy. All rights reserved.
Released under Apache 2.0 license as described in `LICENSES/Apache-2.0.txt`.
Authors: Jack McCarthy
-/

import Hatcher.Sphere.ActionDegree
import Hatcher.Sphere.FixedPointFreeDegree
import Mathlib.Algebra.Group.Subgroup.Ker
import Mathlib.Tactic.FinCases

/-!
# Free actions on even-dimensional spheres

For a free action on a positive even-dimensional sphere, every nonidentity
element has antipodal degree and the degree character is injective. Since its
target is the two-element group `ℤˣ`, every nontrivial acting group is
isomorphic to `ℤ/2`. Conversely, the explicit antipodal involution defines a
free `ℤ/2` action.
-/

noncomputable section

open CategoryTheory

namespace Hatcher.Sphere

private theorem neg_one_pow_succ_of_even
    (n : ℕ) (hn : Even n) :
    (-1 : ℤ) ^ (n + 1) = -1 := by
  obtain ⟨k, rfl⟩ := hn
  rw [pow_succ, pow_add, ← mul_pow]
  norm_num

/-- For a free action on a positive even-dimensional sphere, the degree
character is injective. -/
theorem sphereActionDegreeHom_injective_of_free_even
    {G : Type*} [Group G]
    (n : ℕ) (hn : 0 < n) (heven : Even n)
    (ρ : SphereAction G n) (hfree : ρ.IsFree) :
    Function.Injective (sphereActionDegreeHom n hn ρ) := by
  rw [← MonoidHom.ker_eq_bot_iff]
  apply (Subgroup.eq_bot_iff_forall _).mpr
  intro g hg
  change sphereActionDegreeHom n hn ρ g = 1 at hg
  by_contra hgne
  have hdegree := degree_eq_neg_one_pow_of_fixedPointFree
    n hn (TopCat.isoOfHomeo (ρ g)).hom (hfree g hgne)
  have hcoe := congrArg (fun u : ℤˣ ↦ (u : ℤ)) hg
  rw [sphereActionDegreeHom_coe, hdegree,
    neg_one_pow_succ_of_even n heven] at hcoe
  norm_num at hcoe

private noncomputable def antipodalHomeomorph (n : ℕ) :
    ((TopCat.sphere.{0} n : TopCat.{0}) : Type) ≃ₜ
      ((TopCat.sphere.{0} n : TopCat.{0}) : Type) :=
  TopCat.homeoOfIso (antipodalIso n)

private theorem antipodalHomeomorph_mul_self (n : ℕ) :
    antipodalHomeomorph n * antipodalHomeomorph n = 1 := by
  ext x
  apply (sphereULiftHomeomorph n).injective
  change sphereULiftHomeomorph n
      ((antipodalIso n).hom ((antipodalIso n).hom x)) =
    sphereULiftHomeomorph n x
  rw [sphereULiftHomeomorph_antipodalIso_apply,
    sphereULiftHomeomorph_antipodalIso_apply]
  simp

private theorem multiplicativeZModTwo_eq_one_or_generator
    (z : Multiplicative (ZMod 2)) :
    z = 1 ∨ z = Multiplicative.ofAdd (1 : ZMod 2) := by
  have zmod_cases (a : ZMod 2) : a = 0 ∨ a = 1 := by
    fin_cases a
    · exact Or.inl rfl
    · exact Or.inr rfl
  have hz := zmod_cases z.toAdd
  rcases hz with hz | hz
  · left
    apply Multiplicative.toAdd.injective
    simpa using hz
  · right
    apply Multiplicative.toAdd.injective
    simpa using hz

private noncomputable def antipodalZModTwoActionMap
    (n : ℕ) (z : Multiplicative (ZMod 2)) :
    ((TopCat.sphere.{0} n : TopCat.{0}) : Type) ≃ₜ
      ((TopCat.sphere.{0} n : TopCat.{0}) : Type) :=
  if z = 1 then 1 else antipodalHomeomorph n

/-- The action of `ℤ/2` on the sphere generated by the antipodal
homeomorphism. -/
noncomputable def antipodalZModTwoAction (n : ℕ) :
    SphereAction (Multiplicative (ZMod 2)) n where
  toFun := antipodalZModTwoActionMap n
  map_one' := by simp [antipodalZModTwoActionMap]
  map_mul' x y := by
    obtain rfl | rfl := multiplicativeZModTwo_eq_one_or_generator x
    · simp [antipodalZModTwoActionMap]
    · obtain rfl | rfl := multiplicativeZModTwo_eq_one_or_generator y
      · simp [antipodalZModTwoActionMap]
      · have hgen :
            Multiplicative.ofAdd (1 : ZMod 2) *
                Multiplicative.ofAdd (1 : ZMod 2) = 1 := by
          apply Multiplicative.toAdd.injective
          simpa using CharTwo.add_self_eq_zero (1 : ZMod 2)
        rw [hgen]
        simp [antipodalZModTwoActionMap,
          antipodalHomeomorph_mul_self]

/-- The antipodal homeomorphism has no fixed point. -/
theorem antipodalIso_fixedPointFree (n : ℕ) :
    ∀ x : TopCat.sphere.{0} n, (antipodalIso n).hom x ≠ x := by
  intro x hx
  have hraw := congrArg (sphereULiftHomeomorph n) hx
  rw [sphereULiftHomeomorph_antipodalIso_apply] at hraw
  have hneg :
      -(sphereULiftHomeomorph n x).1 =
        (sphereULiftHomeomorph n x).1 :=
    congrArg Subtype.val hraw
  have hadd :
      (sphereULiftHomeomorph n x).1 +
          (sphereULiftHomeomorph n x).1 = 0 := by
    exact (congrArg
      (fun z : EuclideanSpace ℝ (Fin (n + 1)) ↦
        (sphereULiftHomeomorph n x).1 + z) hneg).symm.trans
          (add_neg_cancel _)
  have htwo :
      (2 : ℝ) • (sphereULiftHomeomorph n x).1 = 0 := by
    simpa [two_smul ℝ] using hadd
  have hzero : (sphereULiftHomeomorph n x).1 = 0 :=
    (smul_eq_zero.mp htwo).resolve_left (by norm_num)
  have hnorm : ‖(sphereULiftHomeomorph n x).1‖ = 1 :=
    norm_eq_of_mem_sphere (sphereULiftHomeomorph n x)
  rw [hzero, norm_zero] at hnorm
  norm_num at hnorm

/-- The explicit antipodal `ℤ/2` action is free. -/
theorem antipodalZModTwoAction_isFree (n : ℕ) :
    (antipodalZModTwoAction n).IsFree := by
  intro z hz x
  obtain rfl | rfl := multiplicativeZModTwo_eq_one_or_generator z
  · exact (hz rfl).elim
  · change (antipodalIso n).hom x ≠ x
    exact antipodalIso_fixedPointFree n x

private theorem sphereActionDegreeHom_surjective_of_nontrivial
    {G : Type*} [Group G] [Nontrivial G]
    (n : ℕ) (hn : 0 < n)
    (ρ : SphereAction G n)
    (hinj : Function.Injective (sphereActionDegreeHom n hn ρ)) :
    Function.Surjective (sphereActionDegreeHom n hn ρ) := by
  obtain ⟨g, hg⟩ := exists_ne (1 : G)
  have hchar : sphereActionDegreeHom n hn ρ g ≠ 1 := by
    intro h
    apply hg
    apply hinj
    simpa using h
  have hneg : sphereActionDegreeHom n hn ρ g = -1 :=
    (Int.units_ne_iff_eq_neg).mp hchar
  intro u
  obtain rfl | rfl := Int.units_eq_one_or u
  · exact ⟨1, (sphereActionDegreeHom n hn ρ).map_one⟩
  · exact ⟨g, hneg⟩

/-- **Hatcher, Proposition 2.29 (printed page 135).** A nontrivial group
admits a free action on a positive even-dimensional sphere exactly when it is
isomorphic to `ℤ/2`; the reverse implication uses the explicit antipodal
action. No finiteness hypothesis on the group is needed. -/
theorem exists_freeSphereAction_iff_mulEquiv_zmodTwo
    {G : Type*} [Group G] [Nontrivial G]
    (n : ℕ) (hn : 0 < n) (heven : Even n) :
    (∃ ρ : SphereAction G n, ρ.IsFree) ↔
      Nonempty (G ≃* Multiplicative (ZMod 2)) := by
  constructor
  · rintro ⟨ρ, hfree⟩
    let χ := sphereActionDegreeHom n hn ρ
    have hinj : Function.Injective χ :=
      sphereActionDegreeHom_injective_of_free_even n hn heven ρ hfree
    have hsurj : Function.Surjective χ :=
      sphereActionDegreeHom_surjective_of_nontrivial n hn ρ hinj
    exact ⟨(MulEquiv.ofBijective χ ⟨hinj, hsurj⟩).trans
      intUnitsMulEquivZModTwo⟩
  · rintro ⟨e⟩
    let ρ : SphereAction G n :=
      (antipodalZModTwoAction n).comp e.toMonoidHom
    refine ⟨ρ, ?_⟩
    intro g hg x
    have heg : e g ≠ 1 := by
      intro h
      apply hg
      exact e.injective (by simpa using h)
    exact antipodalZModTwoAction_isFree n (e g) heg x

end Hatcher.Sphere
