import Hatcher.Covering.SemilocallySimplyConnected

noncomputable section

open Set TopologicalSpace

namespace Hatcher

universe u

variable {X : Type u} [TopologicalSpace X]

/-- Homotopy classes of paths starting at `x₀`, bundled with their endpoint. -/
def UniversalCover (X : Type u) [TopologicalSpace X] (x₀ : X) :=
  Σ x : X, Path.Homotopic.Quotient x₀ x

namespace UniversalCover

variable {x₀ : X}

/-- Endpoint projection from the path-class space. -/
def proj : UniversalCover X x₀ → X := Sigma.fst

/-- The class of the constant path at the chosen basepoint. -/
def basepoint : UniversalCover X x₀ :=
  ⟨x₀, Path.Homotopic.Quotient.refl x₀⟩

/-- Extend a path class through paths contained in `U`. -/
def basicOpen (U : Set X) {x : X} (hx : x ∈ U)
    (γ : Path.Homotopic.Quotient x₀ x) : Set (UniversalCover X x₀) :=
  {q | ∃ (hq : q.1 ∈ U)
      (δ : Path.Homotopic.Quotient (⟨x, hx⟩ : U) ⟨q.1, hq⟩),
      q.2 = γ.trans (δ.map ⟨Subtype.val, continuous_subtype_val⟩)}

/-- Hatcher's topology generated by small-open path extensions. -/
instance instTopologicalSpace : TopologicalSpace (UniversalCover X x₀) :=
  generateFrom {s | ∃ (U : Set X) (_ : IsNullhomotopicOpen U)
      (x : X) (hx : x ∈ U) (γ : Path.Homotopic.Quotient x₀ x),
      s = basicOpen U hx γ}

end UniversalCover

end Hatcher
