/-
Copyright (c) 2026 Jack McCarthy. All rights reserved.
Released under Apache 2.0 license as described in `LICENSES/Apache-2.0.txt`.
Authors: Jack McCarthy
-/

import Hatcher.Excision.AugmentedSmallChains
import Hatcher.MayerVietoris.ShortExact

/-!
# The augmented Mayer–Vietoris chain complex

This file augments the binary-cover Mayer–Vietoris chain complex.  The new
degree-zero short complex is the split sequence
`R ⟶ R ⊞ R ⟶ R` with maps `(𝟙 R, -𝟙 R)` and addition; every successor
degree is the ordinary binary-cover chain sequence.
-/

noncomputable section

open AlgebraicTopology CategoryTheory Limits Simplicial

namespace Hatcher.MayerVietoris

universe w v u

section Preadditive

variable {X : TopCat.{w}}
variable {C : Type u} [Category.{v} C] [Preadditive C]
  [HasCoproducts.{w} C]

local instance : HasFiniteCoproducts C :=
  hasFiniteCoproducts_of_hasCoproducts C

local instance : HasBinaryBiproducts C :=
  HasBinaryBiproducts.of_hasBinaryCoproducts

private noncomputable abbrev subsetChains (A : Set X) (R : C) :
    ChainComplex C ℕ :=
  ((Hatcher.Excision.smallSubcomplexOfSet A : SSet.{w})).chainComplex R

/-- The augmentation on the chains generated by simplices supported in a
fixed subset of the ambient space. -/
private noncomputable def subcomplexChainAugmentation
    (S : (TopCat.toSSet.obj X).Subcomplex) (R : C) :
    (((S : SSet.{w}).chainComplex R).X 0) ⟶ R :=
  (SSet.chainComplexMap S.ι R).f 0 ≫
    Hatcher.Reduced.chainAugmentation R X

set_option backward.isDefEq.respectTransparency false in
private lemma subcomplexChainAugmentation_condition
    (S : (TopCat.toSSet.obj X).Subcomplex) (R : C) :
    ((S : SSet.{w}).chainComplex R).d 1 0 ≫
      subcomplexChainAugmentation S R = 0 := by
  rw [subcomplexChainAugmentation,
    ← (SSet.chainComplexMap S.ι R).comm_assoc]
  change (SSet.chainComplexMap S.ι R).f 1 ≫
    ((((singularChainComplexFunctor C).obj R).obj X).d 1 0 ≫
      Hatcher.Reduced.chainAugmentation R X) = 0
  rw [Hatcher.Reduced.d_chainAugmentation, comp_zero]

set_option backward.isDefEq.respectTransparency false in
private lemma chainComplexMap_f_zero_subcomplexChainAugmentation
    (S T : (TopCat.toSSet.obj X).Subcomplex)
    (f : (S : SSet.{w}) ⟶ (T : SSet.{w})) (R : C) :
    (SSet.chainComplexMap f R).f 0 ≫
        subcomplexChainAugmentation T R =
      subcomplexChainAugmentation S R := by
  apply (S : SSet.{w}).chainComplex_hom_ext
  intro x
  rw [SSet.ι_chainComplexMap_f_assoc]
  dsimp only [subcomplexChainAugmentation]
  simp only [← Category.assoc, SSet.ι_chainComplexMap_f,
    Hatcher.Reduced.ι_chainAugmentation]

/-- Chains supported in one subset, augmented by restriction of the ordinary
singular-chain augmentation. -/
noncomputable def augmentedSubsetChains (A : Set X) (R : C) :
    ChainComplex C ℕ :=
  ChainComplex.augment (subsetChains A R)
    (subcomplexChainAugmentation
      (Hatcher.Excision.smallSubcomplexOfSet A) R)
    (subcomplexChainAugmentation_condition
      (Hatcher.Excision.smallSubcomplexOfSet A) R)

private noncomputable def augmentMap
    {K L : ChainComplex C ℕ} {P : C}
    (εK : K.X 0 ⟶ P) (hK : K.d 1 0 ≫ εK = 0)
    (εL : L.X 0 ⟶ P) (hL : L.d 1 0 ≫ εL = 0)
    (f : K ⟶ L) (hf : εK = f.f 0 ≫ εL) :
    ChainComplex.augment K εK hK ⟶ ChainComplex.augment L εL hL where
  f
    | 0 => 𝟙 P
    | n + 1 => f.f n
  comm' i j _ := by
    match i, j with
    | 0, _ => simp [ChainComplex.augment]
    | 1, 0 => simpa [ChainComplex.augment] using hf.symm
    | _ + 2, 0 => simp [ChainComplex.augment]
    | i + 1, j + 1 => simp [ChainComplex.augment, f.comm]

private noncomputable def augmentIso
    {K L : ChainComplex C ℕ} {P : C}
    (εK : K.X 0 ⟶ P) (hK : K.d 1 0 ≫ εK = 0)
    (εL : L.X 0 ⟶ P) (hL : L.d 1 0 ≫ εL = 0)
    (e : K ≅ L) (he : εK = e.hom.f 0 ≫ εL) :
    ChainComplex.augment K εK hK ≅ ChainComplex.augment L εL hL := by
  have he' : εL = e.inv.f 0 ≫ εK := by
    rw [he, ← Category.assoc, ← HomologicalComplex.comp_f, e.inv_hom_id]
    simp
  exact
    { hom := augmentMap εK hK εL hL e.hom he
      inv := augmentMap εL hL εK hK e.inv he'
      hom_inv_id := by ext (_ | n) <;> simp [augmentMap]
      inv_hom_id := by ext (_ | n) <;> simp [augmentMap] }

/-- The canonical inclusion of a subspace into its ambient space. -/
noncomputable abbrev subspaceInclusion (A : Set X) :
    TopCat.of A ⟶ X :=
  TopCat.ofHom (X := A) ⟨Subtype.val, by fun_prop⟩

/-- The canonical inclusion associated to an inclusion of subsets. -/
noncomputable def subspaceInclusionOfLE {A B : Set X} (h : A ⊆ B) :
    TopCat.of A ⟶ TopCat.of B :=
  TopCat.ofHom (ContinuousMap.inclusion h)

private noncomputable abbrev subspaceInclusionSSetMap (A : Set X) :
    TopCat.toSSet.obj (TopCat.of A) ⟶ TopCat.toSSet.obj X :=
  TopCat.toSSet.map (subspaceInclusion A)

private instance mono_subspaceInclusionSSetMap (A : Set X) :
    Mono (subspaceInclusionSSetMap A) := by
  rw [NatTrans.mono_iff_mono_app]
  intro ⟨⟨n⟩⟩
  rw [CategoryTheory.mono_iff_injective]
  intro x y hxy
  apply (TopCat.toSSetObjEquiv _ _).injective
  ext t
  exact DFunLike.congr_fun
    ((TopCat.toSSetObjEquiv X (Opposite.op ⦋n⦌)).congr_arg hxy) t

/-- The range-factorization map from the singular simplicial set of a
subspace to the ambient singular subcomplex supported in that subspace. -/
noncomputable abbrev subspaceToSubsetSSetMap (A : Set X) :
    TopCat.toSSet.obj (TopCat.of A) ⟶
      (Hatcher.Excision.smallSubcomplexOfSet A : SSet.{w}) :=
  SSet.Subcomplex.toRange (subspaceInclusionSSetMap A)

/-- Supported singular subcomplexes are monotone in the supporting set. -/
lemma smallSubcomplexOfSet_mono {A B : Set X} (h : A ⊆ B) :
    Hatcher.Excision.smallSubcomplexOfSet A ≤
      Hatcher.Excision.smallSubcomplexOfSet B := by
  intro Δ x hx
  rw [Hatcher.Excision.mem_smallSubcomplexOfSet_iff] at hx ⊢
  exact hx.trans h

/-- The canonical simplicial map between supported singular subcomplexes
induced by an inclusion of supporting sets. -/
noncomputable abbrev smallSubcomplexOfSetMap {A B : Set X} (h : A ⊆ B) :
    (Hatcher.Excision.smallSubcomplexOfSet A : SSet.{w}) ⟶
      (Hatcher.Excision.smallSubcomplexOfSet B : SSet.{w}) :=
  SSet.Subcomplex.homOfLE (smallSubcomplexOfSet_mono h)

/-- A subset inclusion induces the canonical map between the corresponding
augmented supported-chain complexes. -/
noncomputable def augmentedSubsetChainsMap {A B : Set X} (h : A ⊆ B)
    (R : C) : augmentedSubsetChains A R ⟶ augmentedSubsetChains B R :=
  augmentMap
    (subcomplexChainAugmentation
      (Hatcher.Excision.smallSubcomplexOfSet A) R)
    (subcomplexChainAugmentation_condition
      (Hatcher.Excision.smallSubcomplexOfSet A) R)
    (subcomplexChainAugmentation
      (Hatcher.Excision.smallSubcomplexOfSet B) R)
    (subcomplexChainAugmentation_condition
      (Hatcher.Excision.smallSubcomplexOfSet B) R)
    (SSet.chainComplexMap (smallSubcomplexOfSetMap h) R)
    (chainComplexMap_f_zero_subcomplexChainAugmentation
      (Hatcher.Excision.smallSubcomplexOfSet A)
      (Hatcher.Excision.smallSubcomplexOfSet B)
      (smallSubcomplexOfSetMap h) R).symm

@[simp]
lemma augmentedSubsetChainsMap_f_zero {A B : Set X} (h : A ⊆ B)
    (R : C) : (augmentedSubsetChainsMap h R).f 0 = 𝟙 R := rfl

@[simp]
lemma augmentedSubsetChainsMap_f_succ {A B : Set X} (h : A ⊆ B)
    (R : C) (n : ℕ) :
    (augmentedSubsetChainsMap h R).f (n + 1) =
      (SSet.chainComplexMap (smallSubcomplexOfSetMap h) R).f n := rfl

private noncomputable def subspaceChainIso (A : Set X) (R : C) :
    ((TopCat.toSSet.obj (TopCat.of A)).chainComplex R) ≅
      subsetChains A R :=
  ((SSet.chainComplexFunctor.{w} C).obj R).mapIso
    (asIso (subspaceToSubsetSSetMap A))

set_option backward.isDefEq.respectTransparency false in
private lemma subspaceChainIso_hom_augmentation
    (A : Set X) (R : C) :
    Hatcher.Reduced.chainAugmentation R (TopCat.of A) =
      (subspaceChainIso A R).hom.f 0 ≫
        subcomplexChainAugmentation
          (Hatcher.Excision.smallSubcomplexOfSet A) R := by
  rw [← Hatcher.Reduced.chainMap_f_zero_chainAugmentation R
      (subspaceInclusion A)]
  dsimp only [AlgebraicTopology.singularChainComplexFunctor,
    subspaceChainIso, Functor.mapIso, asIso,
    subcomplexChainAugmentation]
  rw [← Category.assoc, ← HomologicalComplex.comp_f,
    ← Functor.map_comp, SSet.Subcomplex.toRange_ι]
  rfl

/-- The augmented singular chains of the subspace `A` are canonically
isomorphic to the augmented chains generated by simplices supported in `A`.
The isomorphism is induced by the range factorization of the singular map of
the subtype inclusion. -/
noncomputable def augmentedSubspaceChainIso (A : Set X) (R : C) :
    (Hatcher.Reduced.augmentedSingularChainComplexFunctor R).obj
        (TopCat.of A) ≅
      augmentedSubsetChains A R :=
  augmentIso (Hatcher.Reduced.chainAugmentation R (TopCat.of A))
    (Hatcher.Reduced.d_chainAugmentation R (TopCat.of A))
    (subcomplexChainAugmentation
      (Hatcher.Excision.smallSubcomplexOfSet A) R)
    (subcomplexChainAugmentation_condition
      (Hatcher.Excision.smallSubcomplexOfSet A) R)
    (subspaceChainIso A R) (subspaceChainIso_hom_augmentation A R)

@[simp]
lemma augmentedSubspaceChainIso_hom_f_zero
    (A : Set X) (R : C) :
    (augmentedSubspaceChainIso A R).hom.f 0 = 𝟙 R := rfl

@[simp]
lemma augmentedSubspaceChainIso_inv_f_zero
    (A : Set X) (R : C) :
    (augmentedSubspaceChainIso A R).inv.f 0 = 𝟙 R := rfl

@[simp]
lemma augmentedSubspaceChainIso_hom_f_succ
  (A : Set X) (R : C) (n : ℕ) :
    (augmentedSubspaceChainIso A R).hom.f (n + 1) =
      (SSet.chainComplexMap (subspaceToSubsetSSetMap A) R).f n := by
  simp [augmentedSubspaceChainIso, augmentIso, augmentMap,
    subspaceChainIso]
  rfl

@[simp]
lemma augmentedSubspaceChainIso_inv_f_succ
  (A : Set X) (R : C) (n : ℕ) :
    (augmentedSubspaceChainIso A R).inv.f (n + 1) =
      (SSet.chainComplexMap (inv (subspaceToSubsetSSetMap A)) R).f n := by
  simp [augmentedSubspaceChainIso, augmentIso, augmentMap,
    subspaceChainIso]
  rfl

private lemma subspaceToSubsetSSetMap_naturality
    {A B : Set X} (h : A ⊆ B) :
    subspaceToSubsetSSetMap A ≫ smallSubcomplexOfSetMap h =
      TopCat.toSSet.map (subspaceInclusionOfLE h) ≫
        subspaceToSubsetSSetMap B := by
  rw [← cancel_mono (Hatcher.Excision.smallSubcomplexOfSet B).ι]
  simp only [Category.assoc, SSet.Subcomplex.homOfLE_ι,
    SSet.Subcomplex.toRange_ι]
  rw [← Functor.map_comp]
  rfl

set_option backward.isDefEq.respectTransparency false in
/-- The canonical range-factorization isomorphism is natural for subset
inclusions. -/
@[reassoc]
lemma augmentedSubspaceChainIso_hom_naturality
    {A B : Set X} (h : A ⊆ B) (R : C) :
    (augmentedSubspaceChainIso A R).hom ≫ augmentedSubsetChainsMap h R =
      Hatcher.Reduced.augmentedMap R (subspaceInclusionOfLE h) ≫
        (augmentedSubspaceChainIso B R).hom := by
  ext (_ | n)
  · change 𝟙 R ≫ 𝟙 R = 𝟙 R ≫ 𝟙 R
    simp
  · change
      (SSet.chainComplexMap (subspaceToSubsetSSetMap A) R).f n ≫
          (SSet.chainComplexMap (smallSubcomplexOfSetMap h) R).f n =
        (SSet.chainComplexMap
              (TopCat.toSSet.map (subspaceInclusionOfLE h)) R).f n ≫
          (SSet.chainComplexMap (subspaceToSubsetSSetMap B) R).f n
    rw [← HomologicalComplex.comp_f, ← HomologicalComplex.comp_f,
      ← Functor.map_comp, ← Functor.map_comp,
      subspaceToSubsetSSetMap_naturality h]

/-- The componentwise augmentation on the ordinary biproduct of the two
member chain complexes. -/
private noncomputable def middleChainAugmentation
    (A B : Set X) (R : C) :
    ((subsetChains A R ⊞ subsetChains B R).X 0) ⟶ R ⊞ R :=
  biprod.lift
    ((biprod.fst : subsetChains A R ⊞ subsetChains B R ⟶
        subsetChains A R).f 0 ≫
      subcomplexChainAugmentation
        (Hatcher.Excision.smallSubcomplexOfSet A) R)
    ((biprod.snd : subsetChains A R ⊞ subsetChains B R ⟶
        subsetChains B R).f 0 ≫
      subcomplexChainAugmentation
        (Hatcher.Excision.smallSubcomplexOfSet B) R)

private lemma middleChainAugmentation_condition
    (A B : Set X) (R : C) :
    (subsetChains A R ⊞ subsetChains B R).d 1 0 ≫
      middleChainAugmentation A B R = 0 := by
  apply biprod.hom_ext <;> simp only [zero_comp]
  · rw [Category.assoc, middleChainAugmentation, biprod.lift_fst,
      ← (biprod.fst : subsetChains A R ⊞ subsetChains B R ⟶
        subsetChains A R).comm_assoc,
      subcomplexChainAugmentation_condition, comp_zero]
  · rw [Category.assoc, middleChainAugmentation, biprod.lift_snd,
      ← (biprod.snd : subsetChains A R ⊞ subsetChains B R ⟶
        subsetChains B R).comm_assoc,
      subcomplexChainAugmentation_condition, comp_zero]

/-- The ordinary biproduct of the two member chain complexes, augmented in
degree zero by the two restricted augmentations. -/
noncomputable def augmentedMiddleChains (A B : Set X) (R : C) :
    ChainComplex C ℕ :=
  ChainComplex.augment (subsetChains A R ⊞ subsetChains B R)
    (middleChainAugmentation A B R)
    (middleChainAugmentation_condition A B R)

private noncomputable def augmentedMiddleChainsToLeft
    (A B : Set X) (R : C) :
    augmentedMiddleChains A B R ⟶ augmentedSubsetChains A R where
  f
    | 0 => biprod.fst
    | n + 1 => (biprod.fst : subsetChains A R ⊞ subsetChains B R ⟶
        subsetChains A R).f n
  comm' i j _ := by
    match i, j with
    | 0, _ => simp [augmentedMiddleChains, augmentedSubsetChains,
        ChainComplex.augment]
    | 1, 0 => simp [augmentedMiddleChains, augmentedSubsetChains,
        ChainComplex.augment, middleChainAugmentation]
    | _ + 2, 0 => simp [augmentedMiddleChains, augmentedSubsetChains,
        ChainComplex.augment]
    | i + 1, j + 1 => simp [augmentedMiddleChains, augmentedSubsetChains,
        ChainComplex.augment]

private noncomputable def augmentedMiddleChainsToRight
    (A B : Set X) (R : C) :
    augmentedMiddleChains A B R ⟶ augmentedSubsetChains B R where
  f
    | 0 => biprod.snd
    | n + 1 => (biprod.snd : subsetChains A R ⊞ subsetChains B R ⟶
        subsetChains B R).f n
  comm' i j _ := by
    match i, j with
    | 0, _ => simp [augmentedMiddleChains, augmentedSubsetChains,
        ChainComplex.augment]
    | 1, 0 => simp [augmentedMiddleChains, augmentedSubsetChains,
        ChainComplex.augment, middleChainAugmentation]
    | _ + 2, 0 => simp [augmentedMiddleChains, augmentedSubsetChains,
        ChainComplex.augment]
    | i + 1, j + 1 => simp [augmentedMiddleChains, augmentedSubsetChains,
        ChainComplex.augment]

private noncomputable def augmentedMiddleChainsMap
    (A B : Set X) (R : C) :
    augmentedMiddleChains A B R ⟶
      augmentedSubsetChains A R ⊞ augmentedSubsetChains B R :=
  biprod.lift (augmentedMiddleChainsToLeft A B R)
    (augmentedMiddleChainsToRight A B R)

private noncomputable def augmentedMiddleChainsComponentIso
    (A B : Set X) (R : C) : ∀ n,
    (augmentedMiddleChains A B R).X n ≅
      (augmentedSubsetChains A R ⊞ augmentedSubsetChains B R).X n :=
  fun n => match n with
    | 0 => (HomologicalComplex.biprodXIso
        (augmentedSubsetChains A R) (augmentedSubsetChains B R) 0).symm
    | n + 1 =>
        HomologicalComplex.biprodXIso (subsetChains A R)
            (subsetChains B R) n ≪≫
          (HomologicalComplex.biprodXIso
            (augmentedSubsetChains A R) (augmentedSubsetChains B R)
            (n + 1)).symm

set_option backward.isDefEq.respectTransparency false in
private lemma augmentedMiddleChainsMap_f
    (A B : Set X) (R : C) (n : ℕ) :
    (augmentedMiddleChainsMap A B R).f n =
      (augmentedMiddleChainsComponentIso A B R n).hom := by
  apply HomologicalComplex.biprodX_ext_to
  · obtain _ | n := n
    · simp [augmentedMiddleChainsMap, augmentedMiddleChainsToLeft,
        augmentedMiddleChainsComponentIso]
      rw [← cancel_epi (HomologicalComplex.biprodXIso
        (augmentedSubsetChains A R) (augmentedSubsetChains B R) 0).hom]
      simp
      exact HomologicalComplex.biprodXIso_hom_fst
        (augmentedSubsetChains A R) (augmentedSubsetChains B R) 0
    · simp [augmentedMiddleChainsMap, augmentedMiddleChainsToLeft,
        augmentedMiddleChainsComponentIso]
      rw [← cancel_epi (HomologicalComplex.biprodXIso
        (subsetChains A R) (subsetChains B R) n).inv]
      simp
      rw [← HomologicalComplex.biprodXIso_hom_fst
          (subsetChains A R) (subsetChains B R) n,
        ← HomologicalComplex.biprodXIso_hom_fst
          (augmentedSubsetChains A R) (augmentedSubsetChains B R) (n + 1)]
      simp only [← Category.assoc, Iso.inv_hom_id, Category.id_comp]
      rfl
  · obtain _ | n := n
    · simp [augmentedMiddleChainsMap, augmentedMiddleChainsToRight,
        augmentedMiddleChainsComponentIso]
      rw [← cancel_epi (HomologicalComplex.biprodXIso
        (augmentedSubsetChains A R) (augmentedSubsetChains B R) 0).hom]
      simp
      exact HomologicalComplex.biprodXIso_hom_snd
        (augmentedSubsetChains A R) (augmentedSubsetChains B R) 0
    · simp [augmentedMiddleChainsMap, augmentedMiddleChainsToRight,
        augmentedMiddleChainsComponentIso]
      rw [← cancel_epi (HomologicalComplex.biprodXIso
        (subsetChains A R) (subsetChains B R) n).inv]
      simp
      rw [← HomologicalComplex.biprodXIso_hom_snd
          (subsetChains A R) (subsetChains B R) n,
        ← HomologicalComplex.biprodXIso_hom_snd
          (augmentedSubsetChains A R) (augmentedSubsetChains B R) (n + 1)]
      simp only [← Category.assoc, Iso.inv_hom_id, Category.id_comp]
      rfl

/-- The custom componentwise augmentation of the middle term is canonically
isomorphic to the biproduct of the two singly augmented member complexes. -/
noncomputable def augmentedMiddleChainsIso (A B : Set X) (R : C) :
    augmentedMiddleChains A B R ≅
      augmentedSubsetChains A R ⊞ augmentedSubsetChains B R :=
  HomologicalComplex.Hom.isoOfComponents
    (augmentedMiddleChainsComponentIso A B R) (by
      intro i j hij
      rw [← augmentedMiddleChainsMap_f A B R i,
        ← augmentedMiddleChainsMap_f A B R j]
      exact (augmentedMiddleChainsMap A B R).comm i j)

@[simp]
lemma augmentedMiddleChainsIso_hom_f_zero
    (A B : Set X) (R : C) :
    (augmentedMiddleChainsIso A B R).hom.f 0 =
      (HomologicalComplex.biprodXIso
        (augmentedSubsetChains A R) (augmentedSubsetChains B R) 0).inv := rfl

@[simp]
lemma augmentedMiddleChainsIso_inv_f_zero
    (A B : Set X) (R : C) :
    (augmentedMiddleChainsIso A B R).inv.f 0 =
      (HomologicalComplex.biprodXIso
        (augmentedSubsetChains A R) (augmentedSubsetChains B R) 0).hom := rfl

@[simp]
lemma augmentedMiddleChainsIso_hom_f_succ
    (A B : Set X) (R : C) (n : ℕ) :
    (augmentedMiddleChainsIso A B R).hom.f (n + 1) =
      (HomologicalComplex.biprodXIso
          ((Hatcher.Excision.smallSubcomplexOfSet A : SSet.{w}).chainComplex R)
          ((Hatcher.Excision.smallSubcomplexOfSet B : SSet.{w}).chainComplex R)
          n).hom ≫
        (HomologicalComplex.biprodXIso
          (augmentedSubsetChains A R) (augmentedSubsetChains B R)
          (n + 1)).inv := rfl

@[simp]
lemma augmentedMiddleChainsIso_inv_f_succ
    (A B : Set X) (R : C) (n : ℕ) :
    (augmentedMiddleChainsIso A B R).inv.f (n + 1) =
      (HomologicalComplex.biprodXIso
          (augmentedSubsetChains A R) (augmentedSubsetChains B R)
          (n + 1)).hom ≫
        (HomologicalComplex.biprodXIso
          ((Hatcher.Excision.smallSubcomplexOfSet A : SSet.{w}).chainComplex R)
          ((Hatcher.Excision.smallSubcomplexOfSet B : SSet.{w}).chainComplex R)
          n).inv := rfl

private lemma intersectionToLeftChainMap_augmentation
    (A B : Set X) (R : C) :
    (intersectionToLeftChainMap A B R).f 0 ≫
        subcomplexChainAugmentation
          (Hatcher.Excision.smallSubcomplexOfSet A) R =
      subcomplexChainAugmentation
        (Hatcher.Excision.smallSubcomplexOfSet (A ∩ B)) R := by
  simpa only [intersectionToLeftChainMap] using
    chainComplexMap_f_zero_subcomplexChainAugmentation
      (Hatcher.Excision.smallSubcomplexOfSet (A ∩ B))
      (Hatcher.Excision.smallSubcomplexOfSet A)
      (SSet.Subcomplex.homOfLE (smallCoverBicartSq A B).le₁₂) R

private lemma intersectionToRightChainMap_augmentation
    (A B : Set X) (R : C) :
    (intersectionToRightChainMap A B R).f 0 ≫
        subcomplexChainAugmentation
          (Hatcher.Excision.smallSubcomplexOfSet B) R =
      subcomplexChainAugmentation
        (Hatcher.Excision.smallSubcomplexOfSet (A ∩ B)) R := by
  simpa only [intersectionToRightChainMap] using
    chainComplexMap_f_zero_subcomplexChainAugmentation
      (Hatcher.Excision.smallSubcomplexOfSet (A ∩ B))
      (Hatcher.Excision.smallSubcomplexOfSet B)
      (SSet.Subcomplex.homOfLE (smallCoverBicartSq A B).le₁₃) R

private lemma chainComplexIntersectionMap_augmentation
    (A B : Set X) (R : C) :
    (chainComplexIntersectionMap A B R).f 0 ≫
        middleChainAugmentation A B R =
      subcomplexChainAugmentation
          (Hatcher.Excision.smallSubcomplexOfSet (A ∩ B)) R ≫
        biprod.lift (𝟙 R) (-𝟙 R) := by
  apply biprod.hom_ext
  · simp [middleChainAugmentation, chainComplexIntersectionMap,
      intersectionToLeftChainMap_augmentation]
  · simp [middleChainAugmentation, chainComplexIntersectionMap,
      intersectionToRightChainMap_augmentation]

private lemma middleChainAugmentation_inl
    (A B : Set X) (R : C) :
    (biprod.inl : subsetChains A R ⟶
        subsetChains A R ⊞ subsetChains B R).f 0 ≫
      middleChainAugmentation A B R =
        subcomplexChainAugmentation
            (Hatcher.Excision.smallSubcomplexOfSet A) R ≫
          biprod.inl := by
  apply biprod.hom_ext
  · simp [middleChainAugmentation]
  · simp [middleChainAugmentation]

private lemma middleChainAugmentation_inr
    (A B : Set X) (R : C) :
    (biprod.inr : subsetChains B R ⟶
        subsetChains A R ⊞ subsetChains B R).f 0 ≫
      middleChainAugmentation A B R =
        subcomplexChainAugmentation
            (Hatcher.Excision.smallSubcomplexOfSet B) R ≫
          biprod.inr := by
  apply biprod.hom_ext
  · simp [middleChainAugmentation]
  · simp [middleChainAugmentation]

/-- The augmented intersection map.  It is `(𝟙 R, -𝟙 R)` in degree zero
and the ordinary signed intersection map in each successor degree. -/
noncomputable def augmentedChainComplexIntersectionMap
    (A B : Set X) (R : C) :
    augmentedSubsetChains (A ∩ B) R ⟶ augmentedMiddleChains A B R where
  f
    | 0 => biprod.lift (𝟙 R) (-𝟙 R)
    | n + 1 => (chainComplexIntersectionMap A B R).f n
  comm' i j _ := by
    match i, j with
    | 0, _ => simp [augmentedSubsetChains, augmentedMiddleChains,
        ChainComplex.augment]
    | 1, 0 => exact chainComplexIntersectionMap_augmentation A B R
    | _ + 2, 0 => simp [augmentedSubsetChains, augmentedMiddleChains,
        ChainComplex.augment]
    | i + 1, j + 1 => simp [augmentedSubsetChains,
        augmentedMiddleChains, ChainComplex.augment,
        (chainComplexIntersectionMap A B R).comm]

@[simp]
lemma augmentedChainComplexIntersectionMap_f_zero
    (A B : Set X) (R : C) :
    (augmentedChainComplexIntersectionMap A B R).f 0 =
      biprod.lift (𝟙 R) (-𝟙 R) := rfl

@[simp]
lemma augmentedChainComplexIntersectionMap_f_succ
    (A B : Set X) (R : C) (n : ℕ) :
    (augmentedChainComplexIntersectionMap A B R).f (n + 1) =
      (chainComplexIntersectionMap A B R).f n := rfl

set_option backward.isDefEq.respectTransparency false in
/-- The augmented union map.  It is codiagonal addition in degree zero and
the ordinary union map in each successor degree. -/
noncomputable def augmentedChainComplexUnionMap
    (A B : Set X) (R : C) :
    augmentedMiddleChains A B R ⟶
      Hatcher.Excision.smallAugmentedChainComplex (Bool.rec A B) R where
  f
    | 0 => biprod.desc (𝟙 R) (𝟙 R)
    | n + 1 => (chainComplexUnionMap A B R).f n
  comm' i j _ := by
    match i, j with
    | 0, _ => simp [augmentedMiddleChains,
        Hatcher.Excision.smallAugmentedChainComplex, ChainComplex.augment]
    | 1, 0 =>
        dsimp only [Hatcher.Excision.smallAugmentedChainComplex,
          augmentedMiddleChains, ChainComplex.augment]
        apply HomologicalComplex.biprodX_ext_from
        · simp only [← Category.assoc, chainComplexUnionMap,
            HomologicalComplex.biprod_inl_desc_f,
            middleChainAugmentation_inl]
          apply (Hatcher.Excision.smallSubcomplexOfSet A :
            SSet.{w}).chainComplex_hom_ext
          intro x
          dsimp only [leftToSmallCoverChainMap]
          rw [SSet.ι_chainComplexMap_f_assoc]
          dsimp only [Hatcher.Excision.smallChainAugmentation,
            subcomplexChainAugmentation]
          simp only [← Category.assoc, SSet.ι_chainComplexMap_f,
            Hatcher.Reduced.ι_chainAugmentation]
          simp
        · simp only [← Category.assoc, chainComplexUnionMap,
            HomologicalComplex.biprod_inr_desc_f,
            middleChainAugmentation_inr]
          apply (Hatcher.Excision.smallSubcomplexOfSet B :
            SSet.{w}).chainComplex_hom_ext
          intro x
          dsimp only [rightToSmallCoverChainMap]
          rw [SSet.ι_chainComplexMap_f_assoc]
          dsimp only [Hatcher.Excision.smallChainAugmentation,
            subcomplexChainAugmentation]
          simp only [← Category.assoc, SSet.ι_chainComplexMap_f,
            Hatcher.Reduced.ι_chainAugmentation]
          simp
    | _ + 2, 0 => simp [augmentedMiddleChains,
        Hatcher.Excision.smallAugmentedChainComplex, ChainComplex.augment]
    | i + 1, j + 1 => simp [augmentedMiddleChains,
        Hatcher.Excision.smallAugmentedChainComplex, ChainComplex.augment,
        (chainComplexUnionMap A B R).comm]

@[simp]
lemma augmentedChainComplexUnionMap_f_zero
    (A B : Set X) (R : C) :
    (augmentedChainComplexUnionMap A B R).f 0 =
      biprod.desc (𝟙 R) (𝟙 R) := rfl

@[simp]
lemma augmentedChainComplexUnionMap_f_succ
    (A B : Set X) (R : C) (n : ℕ) :
    (augmentedChainComplexUnionMap A B R).f (n + 1) =
      (chainComplexUnionMap A B R).f n := rfl

/-- The canonical map from augmented chains supported in `A` to the
ambient augmented singular chains. -/
noncomputable def augmentedSubsetChainsToAmbient
    (A : Set X) (R : C) :
    augmentedSubsetChains A R ⟶
      (Hatcher.Reduced.augmentedSingularChainComplexFunctor R).obj X :=
  augmentMap
    (subcomplexChainAugmentation
      (Hatcher.Excision.smallSubcomplexOfSet A) R)
    (subcomplexChainAugmentation_condition
      (Hatcher.Excision.smallSubcomplexOfSet A) R)
    (Hatcher.Reduced.chainAugmentation R X)
    (Hatcher.Reduced.d_chainAugmentation R X)
    (SSet.chainComplexMap
      (Hatcher.Excision.smallSubcomplexOfSet A).ι R)
    rfl

@[simp]
lemma augmentedSubsetChainsToAmbient_f_zero
    (A : Set X) (R : C) :
    (augmentedSubsetChainsToAmbient A R).f 0 = 𝟙 R := rfl

@[simp]
lemma augmentedSubsetChainsToAmbient_f_succ
    (A : Set X) (R : C) (n : ℕ) :
    (augmentedSubsetChainsToAmbient A R).f (n + 1) =
      (SSet.chainComplexMap
        (Hatcher.Excision.smallSubcomplexOfSet A).ι R).f n := rfl

set_option backward.isDefEq.respectTransparency false in
/-- Identifying supported chains with the chains of the actual subspace
takes the direct supported-chain inclusion to the map induced by the
subspace inclusion. -/
@[reassoc]
lemma augmentedSubspaceChainIso_hom_comp_subsetChainsToAmbient
    (A : Set X) (R : C) :
    (augmentedSubspaceChainIso A R).hom ≫
        augmentedSubsetChainsToAmbient A R =
      Hatcher.Reduced.augmentedMap R (subspaceInclusion A) := by
  ext (_ | n)
  · change 𝟙 R ≫ 𝟙 R = 𝟙 R
    simp
  · simp only [HomologicalComplex.comp_f,
      augmentedSubspaceChainIso_hom_f_succ,
      augmentedSubsetChainsToAmbient_f_succ]
    change
      (SSet.chainComplexMap (subspaceToSubsetSSetMap A) R).f n ≫
          (SSet.chainComplexMap
            (Hatcher.Excision.smallSubcomplexOfSet A).ι R).f n =
        (SSet.chainComplexMap
          (TopCat.toSSet.map (subspaceInclusion A)) R).f n
    rw [← HomologicalComplex.comp_f, ← Functor.map_comp,
      SSet.Subcomplex.toRange_ι]

/-- The biproduct of the two augmented supported-chain complexes. -/
noncomputable abbrev augmentedSubsetChainsBiprod
    (A B : Set X) (R : C) : ChainComplex C ℕ :=
  augmentedSubsetChains A R ⊞ augmentedSubsetChains B R

/-- The augmented binary small-cover chain complex, with all endpoints
fixed for downstream composition. -/
noncomputable abbrev augmentedSmallCoverChains
    (A B : Set X) (R : C) : ChainComplex C ℕ :=
  Hatcher.Excision.smallAugmentedChainComplex
    (X := X) (C := C) (Bool.rec A B : Bool → Set X) R

/-- The augmented middle complex mapped to the augmented small-cover
complex. -/
noncomputable def augmentedMiddleToSmallCover
    (A B : Set X) (R : C) :
    augmentedSubsetChainsBiprod A B R ⟶
      augmentedSmallCoverChains A B R :=
  (augmentedMiddleChainsIso A B R).inv ≫
    augmentedChainComplexUnionMap A B R

@[simp]
lemma augmentedMiddleToSmallCover_f
    (A B : Set X) (R : C) (n : ℕ) :
    (augmentedMiddleToSmallCover A B R).f n =
      (augmentedMiddleChainsIso A B R).inv.f n ≫
        (augmentedChainComplexUnionMap A B R).f n := rfl

/-- The canonical inclusion from augmented binary-cover chains to ambient
augmented singular chains. -/
noncomputable abbrev smallCoverAugmentedInclusion
    (A B : Set X) (R : C) :=
  Hatcher.Excision.smallAugmentedChainInclusion
    (X := X) (C := C) (Bool.rec A B : Bool → Set X) R

/-- The augmented middle complex mapped to ambient augmented singular
chains through the small-cover inclusion. -/
noncomputable def augmentedMiddleToAmbient
    (A B : Set X) (R : C) :
    augmentedSubsetChainsBiprod A B R ⟶
      (Hatcher.Reduced.augmentedSingularChainComplexFunctor R).obj X :=
  { f := fun n =>
      (augmentedMiddleToSmallCover A B R).f n ≫
        (smallCoverAugmentedInclusion A B R).f n }

@[simp]
lemma augmentedMiddleToAmbient_f
    (A B : Set X) (R : C) (n : ℕ) :
    (augmentedMiddleToAmbient A B R).f n =
      (augmentedMiddleToSmallCover A B R).f n ≫
        (smallCoverAugmentedInclusion A B R).f n := rfl

private lemma biprodXIso_inv_comp_fst
    (K L : ChainComplex C ℕ) (n : ℕ) :
    (HomologicalComplex.biprodXIso K L n).inv ≫
        (biprod.fst : K ⊞ L ⟶ K).f n = biprod.fst := by
  calc
    _ = (HomologicalComplex.biprodXIso K L n).inv ≫
        ((HomologicalComplex.biprodXIso K L n).hom ≫ biprod.fst) := by
      rw [HomologicalComplex.biprodXIso_hom_fst]
    _ = ((HomologicalComplex.biprodXIso K L n).inv ≫
        (HomologicalComplex.biprodXIso K L n).hom) ≫ biprod.fst := by
      rw [Category.assoc]
    _ = biprod.fst := by rw [Iso.inv_hom_id, Category.id_comp]

private lemma biprodXIso_inv_comp_snd
    (K L : ChainComplex C ℕ) (n : ℕ) :
    (HomologicalComplex.biprodXIso K L n).inv ≫
        (biprod.snd : K ⊞ L ⟶ L).f n = biprod.snd := by
  calc
    _ = (HomologicalComplex.biprodXIso K L n).inv ≫
        ((HomologicalComplex.biprodXIso K L n).hom ≫ biprod.snd) := by
      rw [HomologicalComplex.biprodXIso_hom_snd]
    _ = ((HomologicalComplex.biprodXIso K L n).inv ≫
        (HomologicalComplex.biprodXIso K L n).hom) ≫ biprod.snd := by
      rw [Category.assoc]
    _ = biprod.snd := by rw [Iso.inv_hom_id, Category.id_comp]

@[reassoc]
private lemma biprod_inl_f_comp_biprodXIso_hom
    (K L : ChainComplex C ℕ) (n : ℕ) :
    (biprod.inl : K ⟶ K ⊞ L).f n ≫
        (HomologicalComplex.biprodXIso K L n).hom = biprod.inl := by
  calc
    _ = (biprod.inl ≫ (HomologicalComplex.biprodXIso K L n).inv) ≫
        (HomologicalComplex.biprodXIso K L n).hom := by
      rw [HomologicalComplex.inl_biprodXIso_inv]
    _ = biprod.inl ≫ ((HomologicalComplex.biprodXIso K L n).inv ≫
        (HomologicalComplex.biprodXIso K L n).hom) := by
      rw [Category.assoc]
    _ = biprod.inl := by rw [Iso.inv_hom_id, Category.comp_id]

@[reassoc]
private lemma biprod_inr_f_comp_biprodXIso_hom
    (K L : ChainComplex C ℕ) (n : ℕ) :
    (biprod.inr : L ⟶ K ⊞ L).f n ≫
        (HomologicalComplex.biprodXIso K L n).hom = biprod.inr := by
  calc
    _ = (biprod.inr ≫ (HomologicalComplex.biprodXIso K L n).inv) ≫
        (HomologicalComplex.biprodXIso K L n).hom := by
      rw [HomologicalComplex.inr_biprodXIso_inv]
    _ = biprod.inr ≫ ((HomologicalComplex.biprodXIso K L n).inv ≫
        (HomologicalComplex.biprodXIso K L n).hom) := by
      rw [Category.assoc]
    _ = biprod.inr := by rw [Iso.inv_hom_id, Category.comp_id]

@[reassoc]
private lemma biprod_inl_f_comp_augmentedMiddleChainsIso_inv_f_zero
    (A B : Set X) (R : C) :
    (biprod.inl : augmentedSubsetChains A R ⟶
        augmentedSubsetChains A R ⊞ augmentedSubsetChains B R).f 0 ≫
      (augmentedMiddleChainsIso A B R).inv.f 0 =
        (biprod.inl : R ⟶ R ⊞ R) := by
  rw [augmentedMiddleChainsIso_inv_f_zero]
  dsimp only [augmentedSubsetChains, augmentedMiddleChains,
    ChainComplex.augment]
  rw [biprod_inl_f_comp_biprodXIso_hom]

@[reassoc]
private lemma biprod_inr_f_comp_augmentedMiddleChainsIso_inv_f_zero
    (A B : Set X) (R : C) :
    (biprod.inr : augmentedSubsetChains B R ⟶
        augmentedSubsetChains A R ⊞ augmentedSubsetChains B R).f 0 ≫
      (augmentedMiddleChainsIso A B R).inv.f 0 =
        (biprod.inr : R ⟶ R ⊞ R) := by
  rw [augmentedMiddleChainsIso_inv_f_zero]
  dsimp only [augmentedSubsetChains, augmentedMiddleChains,
    ChainComplex.augment]
  rw [biprod_inr_f_comp_biprodXIso_hom]

@[reassoc]
private lemma biprod_inl_f_comp_augmentedMiddleChainsIso_inv_f_succ
    (A B : Set X) (R : C) (n : ℕ) :
    (biprod.inl : augmentedSubsetChains A R ⟶
        augmentedSubsetChains A R ⊞ augmentedSubsetChains B R).f (n + 1) ≫
      (augmentedMiddleChainsIso A B R).inv.f (n + 1) =
        (biprod.inl : subsetChains A R ⟶
          subsetChains A R ⊞ subsetChains B R).f n := by
  rw [augmentedMiddleChainsIso_inv_f_succ]
  dsimp only [augmentedSubsetChains, augmentedMiddleChains,
    ChainComplex.augment]
  rw [← Category.assoc, biprod_inl_f_comp_biprodXIso_hom]
  change
    (biprod.inl : (subsetChains A R).X n ⟶
        (subsetChains A R).X n ⊞ (subsetChains B R).X n) ≫
      (HomologicalComplex.biprodXIso
        (subsetChains A R) (subsetChains B R) n).inv =
        (biprod.inl : subsetChains A R ⟶
          subsetChains A R ⊞ subsetChains B R).f n
  rw [HomologicalComplex.inl_biprodXIso_inv]

@[reassoc]
private lemma biprod_inr_f_comp_augmentedMiddleChainsIso_inv_f_succ
    (A B : Set X) (R : C) (n : ℕ) :
    (biprod.inr : augmentedSubsetChains B R ⟶
        augmentedSubsetChains A R ⊞ augmentedSubsetChains B R).f (n + 1) ≫
      (augmentedMiddleChainsIso A B R).inv.f (n + 1) =
        (biprod.inr : subsetChains B R ⟶
          subsetChains A R ⊞ subsetChains B R).f n := by
  rw [augmentedMiddleChainsIso_inv_f_succ]
  dsimp only [augmentedSubsetChains, augmentedMiddleChains,
    ChainComplex.augment]
  rw [← Category.assoc, biprod_inr_f_comp_biprodXIso_hom]
  change
    (biprod.inr : (subsetChains B R).X n ⟶
        (subsetChains A R).X n ⊞ (subsetChains B R).X n) ≫
      (HomologicalComplex.biprodXIso
        (subsetChains A R) (subsetChains B R) n).inv =
        (biprod.inr : subsetChains B R ⟶
          subsetChains A R ⊞ subsetChains B R).f n
  rw [HomologicalComplex.inr_biprodXIso_inv]

set_option backward.isDefEq.respectTransparency false in
/-- After identifying the custom augmented middle complex with the
biproduct, the augmented intersection map is the signed lift of the two
canonical subset maps. -/
@[reassoc]
lemma augmentedChainComplexIntersectionMap_comp_middleIso
    (A B : Set X) (R : C) :
    augmentedChainComplexIntersectionMap A B R ≫
        (augmentedMiddleChainsIso A B R).hom =
      biprod.lift
        (augmentedSubsetChainsMap Set.inter_subset_left R)
        (-augmentedSubsetChainsMap Set.inter_subset_right R) := by
  apply biprod.hom_ext
  · ext (_ | n)
    · simp only [HomologicalComplex.comp_f,
        augmentedChainComplexIntersectionMap_f_zero,
        augmentedMiddleChainsIso_hom_f_zero,
        HomologicalComplex.biprod_lift_fst_f,
        augmentedSubsetChainsMap_f_zero, Category.assoc,
        biprodXIso_inv_comp_fst]
      exact biprod.lift_fst (𝟙 R) (-𝟙 R)
    · simp only [HomologicalComplex.comp_f,
        augmentedChainComplexIntersectionMap_f_succ,
        augmentedMiddleChainsIso_hom_f_succ,
        HomologicalComplex.biprod_lift_fst_f,
        augmentedSubsetChainsMap_f_succ, Category.assoc,
        biprodXIso_inv_comp_fst]
      change
        (chainComplexIntersectionMap A B R).f n ≫
            ((HomologicalComplex.biprodXIso
              ((Hatcher.Excision.smallSubcomplexOfSet A : SSet.{w}).chainComplex R)
              ((Hatcher.Excision.smallSubcomplexOfSet B : SSet.{w}).chainComplex R)
              n).hom ≫ biprod.fst) =
          (intersectionToLeftChainMap A B R).f n
      rw [HomologicalComplex.biprodXIso_hom_fst
        ((Hatcher.Excision.smallSubcomplexOfSet A : SSet.{w}).chainComplex R)
        ((Hatcher.Excision.smallSubcomplexOfSet B : SSet.{w}).chainComplex R)
        n]
      rw [chainComplexIntersectionMap,
        HomologicalComplex.biprod_lift_fst_f]
  · ext (_ | n)
    · simp only [HomologicalComplex.comp_f,
        augmentedChainComplexIntersectionMap_f_zero,
        augmentedMiddleChainsIso_hom_f_zero,
        HomologicalComplex.biprod_lift_snd_f,
        augmentedSubsetChainsMap_f_zero, Category.assoc,
        biprodXIso_inv_comp_snd]
      exact biprod.lift_snd (𝟙 R) (-𝟙 R)
    · simp only [HomologicalComplex.comp_f,
        augmentedChainComplexIntersectionMap_f_succ,
        augmentedMiddleChainsIso_hom_f_succ,
        HomologicalComplex.biprod_lift_snd_f,
        augmentedSubsetChainsMap_f_succ, Category.assoc,
        biprodXIso_inv_comp_snd]
      change
        (chainComplexIntersectionMap A B R).f n ≫
            ((HomologicalComplex.biprodXIso
              ((Hatcher.Excision.smallSubcomplexOfSet A : SSet.{w}).chainComplex R)
              ((Hatcher.Excision.smallSubcomplexOfSet B : SSet.{w}).chainComplex R)
              n).hom ≫ biprod.snd) =
          (-intersectionToRightChainMap A B R).f n
      rw [HomologicalComplex.biprodXIso_hom_snd
        ((Hatcher.Excision.smallSubcomplexOfSet A : SSet.{w}).chainComplex R)
        ((Hatcher.Excision.smallSubcomplexOfSet B : SSet.{w}).chainComplex R)
        n]
      rw [chainComplexIntersectionMap,
        HomologicalComplex.biprod_lift_snd_f]

set_option backward.isDefEq.respectTransparency false in
/-- The augmented union map followed by the small-chain inclusion is the
codiagonal of the two canonical maps from supported chains to ambient
augmented singular chains. -/
lemma augmentedMiddleToAmbient_eq
    (A B : Set X) (R : C) :
    augmentedMiddleToAmbient A B R =
      biprod.desc
        (augmentedSubsetChainsToAmbient A R)
        (augmentedSubsetChainsToAmbient B R) := by
  apply biprod.hom_ext'
    (X := augmentedSubsetChains A R)
    (Y := augmentedSubsetChains B R)
    (Z := (Hatcher.Reduced.augmentedSingularChainComplexFunctor R).obj X)
  · rw [biprod.inl_desc]
    ext (_ | n)
    · simp only [HomologicalComplex.comp_f,
        augmentedMiddleToAmbient_f,
        augmentedMiddleToSmallCover_f,
        augmentedChainComplexUnionMap_f_zero,
        smallCoverAugmentedInclusion,
        Hatcher.Excision.smallAugmentedChainInclusion_f_zero,
        augmentedSubsetChainsToAmbient_f_zero, Category.assoc,
        biprod_inl_f_comp_augmentedMiddleChainsIso_inv_f_zero_assoc,
        biprod.inl_desc_assoc]
      dsimp only [augmentedSubsetChains, augmentedSmallCoverChains,
        Hatcher.Excision.smallAugmentedChainComplex, ChainComplex.augment]
      rw [Category.id_comp]
    · simp only [HomologicalComplex.comp_f,
        augmentedMiddleToAmbient_f,
        augmentedMiddleToSmallCover_f,
        augmentedChainComplexUnionMap_f_succ,
        smallCoverAugmentedInclusion,
        Hatcher.Excision.smallAugmentedChainInclusion_f_succ,
        augmentedSubsetChainsToAmbient_f_succ, Category.assoc,
        biprod_inl_f_comp_augmentedMiddleChainsIso_inv_f_succ_assoc,
        chainComplexUnionMap,
        HomologicalComplex.biprod_inl_desc_f_assoc]
      dsimp only [leftToSmallCoverChainMap]
      rw [← HomologicalComplex.comp_f, ← Functor.map_comp,
        SSet.Subcomplex.homOfLE_ι]
  · rw [biprod.inr_desc]
    ext (_ | n)
    · simp only [HomologicalComplex.comp_f,
        augmentedMiddleToAmbient_f,
        augmentedMiddleToSmallCover_f,
        augmentedChainComplexUnionMap_f_zero,
        smallCoverAugmentedInclusion,
        Hatcher.Excision.smallAugmentedChainInclusion_f_zero,
        augmentedSubsetChainsToAmbient_f_zero, Category.assoc,
        biprod_inr_f_comp_augmentedMiddleChainsIso_inv_f_zero_assoc,
        biprod.inr_desc_assoc]
      dsimp only [augmentedSubsetChains, augmentedSmallCoverChains,
        Hatcher.Excision.smallAugmentedChainComplex, ChainComplex.augment]
      rw [Category.id_comp]
    · simp only [HomologicalComplex.comp_f,
        augmentedMiddleToAmbient_f,
        augmentedMiddleToSmallCover_f,
        augmentedChainComplexUnionMap_f_succ,
        smallCoverAugmentedInclusion,
        Hatcher.Excision.smallAugmentedChainInclusion_f_succ,
        augmentedSubsetChainsToAmbient_f_succ, Category.assoc,
        biprod_inr_f_comp_augmentedMiddleChainsIso_inv_f_succ_assoc,
        chainComplexUnionMap,
        HomologicalComplex.biprod_inr_desc_f_assoc]
      dsimp only [rightToSmallCoverChainMap]
      rw [← HomologicalComplex.comp_f, ← Functor.map_comp,
        SSet.Subcomplex.homOfLE_ι]

@[reassoc (attr := simp)]
lemma augmentedChainComplexIntersectionMap_comp_unionMap
    (A B : Set X) (R : C) :
    augmentedChainComplexIntersectionMap A B R ≫
      augmentedChainComplexUnionMap A B R = 0 := by
  ext (_ | n)
  · change biprod.lift (𝟙 R) (-𝟙 R) ≫
      biprod.desc (𝟙 R) (𝟙 R) = 0
    simp
  · change (chainComplexIntersectionMap A B R).f n ≫
      (chainComplexUnionMap A B R).f n = 0
    rw [← HomologicalComplex.comp_f,
      chainComplexIntersectionMap_comp_chainComplexUnionMap]
    rfl

/-- **Hatcher, §2.2 (page 150).** The augmented binary-cover
Mayer–Vietoris chain complex. -/
noncomputable def augmentedChainComplexShortComplex
    (A B : Set X) (R : C) : ShortComplex (ChainComplex C ℕ) :=
  ShortComplex.mk (augmentedChainComplexIntersectionMap A B R)
    (augmentedChainComplexUnionMap A B R)
    (augmentedChainComplexIntersectionMap_comp_unionMap A B R)

end Preadditive

section Abelian

variable {X : TopCat.{w}}
variable {C : Type u} [Category.{v} C] [Abelian C]
  [HasCoproducts.{w} C]

local instance : HasFiniteCoproducts C :=
  hasFiniteCoproducts_of_hasCoproducts C

local instance : HasBinaryBiproducts C :=
  HasBinaryBiproducts.of_hasBinaryCoproducts

set_option backward.isDefEq.respectTransparency false in
/-- **Hatcher, §2.2 (page 150).** The augmented binary-cover chain complex
is short exact for arbitrary subsets of the ambient space. -/
theorem augmentedChainComplexShortComplex_shortExact
    (A B : Set X) (R : C) :
    (augmentedChainComplexShortComplex A B R).ShortExact := by
  apply HomologicalComplex.shortExact_of_degreewise_shortExact
  intro i
  obtain _ | n := i
  · change (ShortComplex.mk (biprod.lift (𝟙 R) (-𝟙 R))
      (biprod.desc (𝟙 R) (𝟙 R)) (by simp)).ShortExact
    apply ShortComplex.Splitting.shortExact
    exact
      { r := biprod.fst
        s := biprod.inr
        f_r := by simp
        s_g := by simp
        id := by ext <;> simp }
  · change ((chainComplexShortComplex A B R).map
      (HomologicalComplex.eval C (ComplexShape.down ℕ) n)).ShortExact
    have h := chainComplexShortComplex_shortExact C A B R
    have := h.mono_f
    have := h.epi_g
    exact h.map (HomologicalComplex.eval C (ComplexShape.down ℕ) n)

end Abelian

end Hatcher.MayerVietoris
