/-
Copyright (c) 2026 Jack McCarthy. All rights reserved.
Released under Apache 2.0 license as described in `LICENSES/Apache-2.0.txt`.
Authors: Jack McCarthy
-/

import Hatcher.Excision.SmallSimplices
import Mathlib.Algebra.Homology.CommSq
import Mathlib.Algebra.Homology.HomologicalComplexBiprod
import Mathlib.AlgebraicTopology.SimplicialSet.SubcomplexColimits

/-!
# The Mayer–Vietoris chain complex

For two subsets of a space, this file constructs the chain complex

`C_*(A ∩ B) ⟶ C_*(A) ⊞ C_*(B) ⟶ C_*^{A+B}(X)`

with maps `x ↦ (x, -x)` and `(x, y) ↦ x + y`. No cover hypothesis is
needed for this construction.
-/

noncomputable section

open AlgebraicTopology CategoryTheory Limits Simplicial

namespace Hatcher.MayerVietoris

universe w v u

variable {X : TopCat.{w}}
variable {C : Type u} [Category.{v} C] [Preadditive C]
  [HasCoproducts.{w} C]

local instance : HasFiniteCoproducts C :=
  hasFiniteCoproducts_of_hasCoproducts C

local instance : HasBinaryBiproducts C :=
  HasBinaryBiproducts.of_hasBinaryCoproducts

/-- The chain complex generated by singular simplices whose images lie in
`A` or in `B`. -/
noncomputable abbrev smallCoverChains (A B : Set X) (R : C) :
    ChainComplex C ℕ :=
  ((Hatcher.Excision.smallSubcomplex (Bool.rec A B) : SSet.{w})).chainComplex R

/-- The intersection and the two members of a binary family form a
bicartesian square with its small-cover subcomplex. -/
theorem smallCoverBicartSq (A B : Set X) :
    SSet.Subcomplex.BicartSq
      (Hatcher.Excision.smallSubcomplexOfSet (A ∩ B))
      (Hatcher.Excision.smallSubcomplexOfSet A)
      (Hatcher.Excision.smallSubcomplexOfSet B)
      (Hatcher.Excision.smallSubcomplex (Bool.rec A B)) where
  sup_eq := by
    simpa using
      (Hatcher.Excision.smallSubcomplex_bool (X := X) (Bool.rec A B)).symm
  inf_eq := (Hatcher.Excision.smallSubcomplexOfSet_inter A B).symm

/-- The canonical chain map from intersection chains to chains supported in
`A`. -/
noncomputable def intersectionToLeftChainMap (A B : Set X) (R : C) :
    ((Hatcher.Excision.smallSubcomplexOfSet (A ∩ B) : SSet.{w})).chainComplex R ⟶
      ((Hatcher.Excision.smallSubcomplexOfSet A : SSet.{w})).chainComplex R :=
  SSet.chainComplexMap
    (SSet.Subcomplex.homOfLE (smallCoverBicartSq A B).le₁₂) R

/-- The canonical chain map from intersection chains to chains supported in
`B`. -/
noncomputable def intersectionToRightChainMap (A B : Set X) (R : C) :
    ((Hatcher.Excision.smallSubcomplexOfSet (A ∩ B) : SSet.{w})).chainComplex R ⟶
      ((Hatcher.Excision.smallSubcomplexOfSet B : SSet.{w})).chainComplex R :=
  SSet.chainComplexMap
    (SSet.Subcomplex.homOfLE (smallCoverBicartSq A B).le₁₃) R

/-- The canonical chain map from chains supported in `A` to the binary
small-cover chains. -/
noncomputable def leftToSmallCoverChainMap (A B : Set X) (R : C) :
    ((Hatcher.Excision.smallSubcomplexOfSet A : SSet.{w})).chainComplex R ⟶
      smallCoverChains A B R :=
  SSet.chainComplexMap
    (SSet.Subcomplex.homOfLE (smallCoverBicartSq A B).le₂₄) R

/-- The canonical chain map from chains supported in `B` to the binary
small-cover chains. -/
noncomputable def rightToSmallCoverChainMap (A B : Set X) (R : C) :
    ((Hatcher.Excision.smallSubcomplexOfSet B : SSet.{w})).chainComplex R ⟶
      smallCoverChains A B R :=
  SSet.chainComplexMap
    (SSet.Subcomplex.homOfLE (smallCoverBicartSq A B).le₃₄) R

@[reassoc]
lemma intersectionToLeftChainMap_comp_leftToSmallCoverChainMap
    (A B : Set X) (R : C) :
    intersectionToLeftChainMap A B R ≫ leftToSmallCoverChainMap A B R =
      intersectionToRightChainMap A B R ≫
        rightToSmallCoverChainMap A B R := by
  simpa only [intersectionToLeftChainMap, leftToSmallCoverChainMap,
    intersectionToRightChainMap, rightToSmallCoverChainMap,
    ← Functor.map_comp] using
      congrArg (((SSet.chainComplexFunctor.{w} C).obj R).map)
        (smallCoverBicartSq A B).isPushout.w

/-- The signed map `x ↦ (x, -x)` from intersection chains to the
biproduct of the two member chain complexes. -/
noncomputable def chainComplexIntersectionMap (A B : Set X) (R : C) :
    ((Hatcher.Excision.smallSubcomplexOfSet (A ∩ B) : SSet.{w})).chainComplex R ⟶
      ((Hatcher.Excision.smallSubcomplexOfSet A : SSet.{w})).chainComplex R ⊞
        ((Hatcher.Excision.smallSubcomplexOfSet B : SSet.{w})).chainComplex R :=
  biprod.lift (intersectionToLeftChainMap A B R)
    (-intersectionToRightChainMap A B R)

/-- The addition map `(x, y) ↦ x + y` from the two member chain complexes
to the binary small-cover chain complex. -/
noncomputable def chainComplexUnionMap (A B : Set X) (R : C) :
    ((Hatcher.Excision.smallSubcomplexOfSet A : SSet.{w})).chainComplex R ⊞
        ((Hatcher.Excision.smallSubcomplexOfSet B : SSet.{w})).chainComplex R ⟶
      smallCoverChains A B R :=
  biprod.desc (leftToSmallCoverChainMap A B R)
    (rightToSmallCoverChainMap A B R)

@[reassoc (attr := simp)]
lemma chainComplexIntersectionMap_comp_chainComplexUnionMap
    (A B : Set X) (R : C) :
    chainComplexIntersectionMap A B R ≫ chainComplexUnionMap A B R = 0 := by
  simp [chainComplexIntersectionMap, chainComplexUnionMap,
    intersectionToLeftChainMap_comp_leftToSmallCoverChainMap]

/-- **Hatcher, §2.2.** The binary-cover Mayer–Vietoris chain complex, with
the source sign convention `x ↦ (x, -x)` and target map
`(x, y) ↦ x + y`. -/
noncomputable def chainComplexShortComplex (A B : Set X) (R : C) :
    ShortComplex (ChainComplex C ℕ) :=
  ShortComplex.mk (chainComplexIntersectionMap A B R)
    (chainComplexUnionMap A B R)
    (chainComplexIntersectionMap_comp_chainComplexUnionMap A B R)

end Hatcher.MayerVietoris
