/-
Copyright (c) 2026 Joël Riou. All rights reserved.
Copyright (c) 2026 Jack McCarthy. All rights reserved.
Released under Apache 2.0 license as described in `LICENSES/Apache-2.0.txt`.
Authors: Joël Riou, Jack McCarthy

This file adapts the eventual-smallness argument from `joelriou/excision` at
commit `8b56cd0c8e5f39a7c2f36418c80b298e469596a6` to the Mathlib version pinned
by this project.
-/

import Hatcher.Excision.SingularSubdivision
import Hatcher.Excision.SubdivisionDiameter
import Mathlib.Topology.MetricSpace.Bounded

/-!
# Eventually small singular simplices

For a family of subsets whose interiors cover a space, sufficiently many
barycentric subdivisions of each singular simplex have image in a member of
the family.  The subdivision depth is allowed to depend on the simplex.
-/

noncomputable section

open AlgebraicTopology CategoryTheory Limits Simplicial Opposite Convexity

namespace Hatcher.Excision

universe w

variable {X : TopCat.{w}} {ι : Type*} {U : ι → Set X}

/-- The simplicial subcomplex of singular simplices whose image is contained
in `V`. -/
noncomputable abbrev smallSubcomplexOfSet (V : Set X) :
    (TopCat.toSSet.obj X).Subcomplex :=
  SSet.Subcomplex.range
    (TopCat.toSSet.map
      (TopCat.ofHom (X := V) ⟨Subtype.val, by fun_prop⟩))

lemma mem_smallSubcomplexOfSet_iff (V : Set X) {n : ℕ}
    (s : TopCat.toSSet.obj X _⦋n⦌) :
    s ∈ (smallSubcomplexOfSet V).obj _ ↔
      Set.range (TopCat.toSSetObjEquiv _ _ s) ⊆ V := by
  simp only [smallSubcomplexOfSet, Subfunctor.range_obj, Set.mem_range]
  refine ⟨?_, fun h ↦ ?_⟩
  · rintro ⟨s, rfl⟩
    obtain ⟨f, rfl⟩ := (TopCat.toSSetObjEquiv _ _).symm.surjective s
    change Set.range (Subtype.val ∘ f) ⊆ V
    rintro _ ⟨u, rfl⟩
    simp
  · obtain ⟨f, rfl⟩ := (TopCat.toSSetObjEquiv _ _).symm.surjective s
    exact ⟨(TopCat.toSSetObjEquiv _ _).symm
      ⟨fun x ↦ ⟨f x, h (by simp)⟩, by fun_prop⟩, rfl⟩

lemma smallSubcomplexOfSet_inter (V₁ V₂ : Set X) :
    smallSubcomplexOfSet (V₁ ∩ V₂) =
      smallSubcomplexOfSet V₁ ⊓ smallSubcomplexOfSet V₂ := by
  ext ⟨⟨n⟩⟩
  simp only [mem_smallSubcomplexOfSet_iff, Set.subset_inter_iff,
    Subfunctor.min_obj, Set.mem_inter_iff]

/-- The simplicial subcomplex generated by singular simplices whose image is
contained in one member of `U`. -/
noncomputable def smallSubcomplex (U : ι → Set X) :
    (TopCat.toSSet.obj X).Subcomplex :=
  ⨆ i, smallSubcomplexOfSet (U i)

lemma smallSubcomplex_bool (U : Bool → Set X) :
    smallSubcomplex U =
      smallSubcomplexOfSet (U false) ⊔ smallSubcomplexOfSet (U true) := by
  dsimp [smallSubcomplex]
  refine le_antisymm ?_ ?_
  · simp
  · simp only [sup_le_iff]
    exact ⟨le_iSup (fun i ↦ smallSubcomplexOfSet (U i)) false,
      le_iSup (fun i ↦ smallSubcomplexOfSet (U i)) true⟩

lemma mem_smallSubcomplex_iff {n : ℕ}
    (s : TopCat.toSSet.obj X _⦋n⦌) :
    s ∈ (smallSubcomplex U).obj _ ↔
      ∃ i, Set.range (TopCat.toSSetObjEquiv _ _ s) ⊆ U i := by
  simp only [smallSubcomplex, Subfunctor.iSup_obj, Set.mem_iUnion,
    mem_smallSubcomplexOfSet_iff]

lemma mem_smallSubcomplex_iff_exists_lift {n : ℕ}
    (s : TopCat.toSSet.obj X _⦋n⦌) :
    s ∈ (smallSubcomplex U).obj _ ↔
      ∃ (i : ι) (t : TopCat.toSSet.obj (TopCat.of (U i)) _⦋n⦌),
        (TopCat.toSSet.map
          (TopCat.ofHom ⟨Subtype.val, by fun_prop⟩)).app _ t = s := by
  rw [mem_smallSubcomplex_iff]
  refine exists_congr (fun i ↦ ⟨fun h ↦ ?_, ?_⟩)
  · obtain ⟨f, rfl⟩ := (TopCat.toSSetObjEquiv _ _).symm.surjective s
    exact ⟨(TopCat.toSSetObjEquiv _ _).symm
      ⟨fun x ↦ ⟨f x, h (by simp)⟩, by fun_prop⟩, rfl⟩
  · rintro ⟨t, rfl⟩
    obtain ⟨t, rfl⟩ := (TopCat.toSSetObjEquiv _ _).symm.surjective t
    rintro _ ⟨x, rfl⟩
    exact (t x).prop

lemma singularSubdivision_mem_smallSubcomplex {n : ℕ}
    (s : TopCat.toSSet.obj X _⦋n⦌)
    (hs : s ∈ (smallSubcomplex U).obj _)
    (σ : Equiv.Perm (Fin (n + 1))) :
    singularSubdivision s σ ∈ (smallSubcomplex U).obj _ := by
  rw [mem_smallSubcomplex_iff] at hs ⊢
  obtain ⟨i, hi⟩ := hs
  exact ⟨i, (singularSubdivision_range_subset s σ).trans hi⟩

/-- The condition that the interiors of a family of subsets cover the ambient
space. -/
structure SmallSimplicesCondition (U : ι → Set X) : Prop where
  iUnion_interior : ⋃ i, interior (U i) = Set.univ

namespace SmallSimplicesCondition

variable (hU : SmallSimplicesCondition U)

include hU in
protected lemma iUnion : ⋃ i, U i = Set.univ := by
  rw [← Set.univ_subset_iff, ← hU.iUnion_interior]
  exact Set.iUnion_subset
    (fun i ↦ interior_subset.trans (Set.subset_iUnion _ i))

include hU in
lemma smallSubcomplex_obj_zero :
    (smallSubcomplex U).obj (op ⦋0⦌) = Set.univ := by
  ext x
  obtain ⟨x, rfl⟩ := TopCat.toSSetObj₀Equiv.symm.surjective x
  have hx := Set.mem_univ x
  rw [← hU.iUnion, Set.mem_iUnion] at hx
  obtain ⟨i, hi⟩ := hx
  simp only [mem_smallSubcomplex_iff, Set.mem_univ, iff_true]
  refine ⟨i, ?_⟩
  rintro _ ⟨s, rfl⟩
  exact hi

end SmallSimplicesCondition

/-- All permutation-indexed subsimplices after `k` subdivisions are small. -/
def IteratedSubdivisionIsSmall (U : ι → Set X) {n : ℕ}
    (s : TopCat.toSSet.obj X _⦋n⦌) (k : ℕ) : Prop :=
  ∀ σ : Fin k → Equiv.Perm (Fin (n + 1)),
    singularSubdivisionIter s σ ∈ (smallSubcomplex U).obj _

namespace IteratedSubdivisionIsSmall

lemma succ {n : ℕ} {s : TopCat.toSSet.obj X _⦋n⦌} {k : ℕ}
    (hs : IteratedSubdivisionIsSmall U s k) :
    IteratedSubdivisionIsSmall U s (k + 1) :=
  fun σ ↦ by
    rw [singularSubdivisionIter_succ]
    exact singularSubdivision_mem_smallSubcomplex _ (hs _) _

lemma face {n : ℕ} {s : TopCat.toSSet.obj X _⦋n + 1⦌} {k : ℕ}
    (hs : IteratedSubdivisionIsSmall U s k) (i : Fin (n + 2)) :
    IteratedSubdivisionIsSmall U ((TopCat.toSSet.obj X).δ i s) k := by
  intro σ
  obtain ⟨σ', i', h⟩ := exists_singularSubdivisionIter_face s i σ
  rw [h]
  exact (smallSubcomplex U).map _ (hs _)

lemma of_le {n : ℕ} {s : TopCat.toSSet.obj X _⦋n⦌} {k k' : ℕ}
    (hs : IteratedSubdivisionIsSmall U s k) (h : k ≤ k') :
    IteratedSubdivisionIsSmall U s k' := by
  obtain ⟨i, h⟩ := Nat.le.dest h
  induction i generalizing k k' with
  | zero =>
    obtain rfl : k = k' := by omega
    exact hs
  | succ i ih =>
    obtain rfl : k + i + 1 = k' := by omega
    exact (ih hs (by omega) rfl).succ

end IteratedSubdivisionIsSmall

lemma iteratedSubdivisionIsSmall_zero_iff {n : ℕ}
    (s : TopCat.toSSet.obj X _⦋n⦌) :
    IteratedSubdivisionIsSmall U s 0 ↔
      s ∈ (smallSubcomplex U).obj _ := by
  simp [IteratedSubdivisionIsSmall]

private def simplexCoordinateAffineMap (n : ℕ) :
    ConvexSpace.AffineMap ℝ (StdSimplex ℝ (Fin (n + 1)))
      (Fin (n + 1) → ℝ) where
  toFun s := s.weights
  isAffineMap_toFun :=
    IsAffineMap.pi (fun i ↦
      (StdSimplex.isAffineMap_weights ℝ (Fin (n + 1))).finsuppEval i)

/-- Every singular simplex becomes small after a simplex-dependent finite
number of barycentric subdivisions. -/
theorem exists_iteratedSubdivision_mem_smallSubcomplex
    (hU : SmallSimplicesCondition U) {n : ℕ}
    (s : TopCat.toSSet.obj X _⦋n⦌) :
    ∃ k, IteratedSubdivisionIsSmall U s k := by
  obtain ⟨f, rfl⟩ := (TopCat.toSSetObjEquiv _ _).symm.surjective s
  let V (i : ι) : Set (StdSimplex ℝ (Fin (n + 1))) :=
    f ⁻¹' (interior (U i))
  let α : StdSimplex ℝ (Fin (n + 1)) ≃ₜ
      Set.range (simplexCoordinateAffineMap n) :=
    (StdSimplex.isEmbedding_toFun_comp_weights ℝ (Fin (n + 1))).toHomeomorph
  have : CompactSpace (Set.range (simplexCoordinateAffineMap n)) :=
    isCompact_iff_compactSpace.mp (isCompact_range (by fun_prop))
  let V' (i : ι) := α '' V i
  obtain ⟨ε, hε₀, hε⟩ := CompactSpace.lebesgue_number_lemma V'
    (fun i ↦ by
      simpa [V', V] using f.continuous.isOpen_preimage _ isOpen_interior)
    (by
      simp [V', V, ← Set.image_iUnion, ← Set.preimage_iUnion,
        hU.iUnion_interior])
  let s₀ := ConvexSpace.AffineMap.id (R := ℝ)
    (StdSimplex ℝ (Fin (n + 1)))
  suffices ∃ k, ∀ σ : Fin k → Equiv.Perm (Fin (n + 1)),
      diam ((simplexCoordinateAffineMap n).comp
        (affineSubdivisionIter s₀ σ)) ≤ ε by
    obtain ⟨k, hk⟩ := this
    refine ⟨k, fun σ ↦ ?_⟩
    rw [mem_smallSubcomplex_iff]
    obtain ⟨i, hi⟩ := hε (Set.range (α ∘ affineSubdivisionIter s₀ σ))
      (Set.range_nonempty _) (by
        have hdiam := hk σ
        dsimp [diam, Metric.diam] at hdiam ⊢
        rw [Set.range_comp, ← isometry_subtype_coe.ediam_image]
        convert hdiam
        aesop)
    refine ⟨i, ?_⟩
    rintro _ ⟨x, rfl⟩
    refine interior_subset ?_
    simpa [V', V, singularSubdivisionIter_toSSetObjEquiv_symm] using!
      hi (Set.mem_range_self x)
  let δ := diam ((simplexCoordinateAffineMap n).comp s₀)
  have hδ : 0 ≤ δ := diam_nonneg _
  obtain hδpos | hδzero := hδ.lt_or_eq'
  · have hεδ : 0 < ε / δ := by positivity
    obtain ⟨k, hk⟩ := exists_pow_lt_of_lt_one hεδ
      (y := (n / (n + 1) : ℝ)) (by
        rw [div_lt_one (by positivity)]
        simp)
    refine ⟨k, fun σ ↦ ?_⟩
    rw [affineMap_comp_affineSubdivisionIter]
    refine (affineSubdivisionIter_diameter_le
      ((simplexCoordinateAffineMap n).comp s₀) σ).trans ?_
    exact le_of_le_of_eq
      (mul_le_mul_of_nonneg_right hk.le (diam_nonneg _))
      (div_mul_cancel₀ ε hδpos.ne')
  · exact ⟨0, by simp [δ, hδzero, hε₀.le]⟩

end Hatcher.Excision
