import Hatcher.VanKampen.IndexedConeAttachment

/-!
# Hatcher's auxiliary cell-attachment space

This file enlarges an indexed cone attachment by a common interval spine and
one square strip for each attached cell.  A strip's bottom edge follows the
chosen path from the common basepoint to its attaching point, its left edge is
the common spine, and its right edge follows a truncated radial segment in the
cell.  The top edge remains free.
-/

noncomputable section

open Topology
open scoped unitInterval ContinuousMap

namespace Hatcher.VanKampen

universe u

namespace AuxiliaryCellAttachment

/-- The radial height on a strip's right edge.  It runs from height `1` to
height `1/2`, so it never reaches the cone apex at height `0`. -/
def truncatedRadialHeight : C(I, I) where
  toFun t := ⟨1 - (t : ℝ) / 2, by
    constructor
    · nlinarith [t.property.2]
    · nlinarith [t.property.1]⟩
  continuous_toFun := by fun_prop

@[simp] theorem truncatedRadialHeight_zero : truncatedRadialHeight 0 = 1 := by
  apply Subtype.ext
  simp [truncatedRadialHeight]

@[simp] theorem truncatedRadialHeight_one :
    truncatedRadialHeight 1 = ⟨(1 : ℝ) / 2, by norm_num⟩ := by
  apply Subtype.ext
  change 1 - (1 : ℝ) / 2 = 1 / 2
  ring

theorem truncatedRadialHeight_pos (t : I) : 0 < truncatedRadialHeight t := by
  change 0 < 1 - (t : ℝ) / 2
  nlinarith [t.property.2]

@[simp] theorem truncatedRadialHeight_ne_zero (t : I) :
    truncatedRadialHeight t ≠ 0 :=
  ne_of_gt (truncatedRadialHeight_pos t)

/-- Before quotienting: the indexed attachment, a common interval spine, and
one square for every attached cell. -/
abbrev Prequotient {X J : Type u} {S : J → Type u}
    (f : ∀ j, S j → X) :=
  Hatcher.VanKampen.IndexedConeAttachment f ⊕
    (I ⊕ Sigma (fun _j : J ↦ I × I))

/-- Canonical representatives for the auxiliary strip gluings.  The bottom
edge is normalized first so its corners agree with the path endpoint
equations. -/
def normalForm {X J : Type u} {S : J → Type u}
    [TopologicalSpace X]
    (f : ∀ j, S j → X) (s₀ : ∀ j, S j) (x₀ : X)
    (γ : ∀ j, Path x₀ (f j (s₀ j))) :
    Prequotient f → Prequotient f
  | Sum.inl y => Sum.inl y
  | Sum.inr (Sum.inl t) =>
      if t = 0 then
        Sum.inl (IndexedConeAttachment.base f x₀)
      else
        Sum.inr (Sum.inl t)
  | Sum.inr (Sum.inr ⟨j, (a, t)⟩) =>
      if t = 0 then
        Sum.inl (IndexedConeAttachment.base f (γ j a))
      else if a = 0 then
        Sum.inr (Sum.inl t)
      else if a = 1 then
        Sum.inl (IndexedConeAttachment.cylinder
          f j (s₀ j) (truncatedRadialHeight t))
      else
        Sum.inr (Sum.inr ⟨j, (a, t)⟩)

/-- The equivalence relation generated by the normal form for the spine and
strip boundary identifications. -/
def setoid {X J : Type u} {S : J → Type u}
    [TopologicalSpace X]
    (f : ∀ j, S j → X) (s₀ : ∀ j, S j) (x₀ : X)
    (γ : ∀ j, Path x₀ (f j (s₀ j))) : Setoid (Prequotient f) :=
  Setoid.ker (normalForm f s₀ x₀ γ)

end AuxiliaryCellAttachment

/-- Hatcher's strip-enlarged model for an indexed cone attachment. -/
def AuxiliaryCellAttachment {X J : Type u} {S : J → Type u}
    [TopologicalSpace X]
    (f : ∀ j, S j → X) (s₀ : ∀ j, S j) (x₀ : X)
    (γ : ∀ j, Path x₀ (f j (s₀ j))) : Type u :=
  Quotient (AuxiliaryCellAttachment.setoid f s₀ x₀ γ)

namespace AuxiliaryCellAttachment

variable {X J : Type u} {S : J → Type u}
variable [TopologicalSpace X] [∀ j, TopologicalSpace (S j)]
variable (f : ∀ j, S j → X) (s₀ : ∀ j, S j) (x₀ : X)
variable (γ : ∀ j, Path x₀ (f j (s₀ j)))

/-- The quotient topology on the auxiliary attachment. -/
instance instTopologicalSpace :
    TopologicalSpace (Hatcher.VanKampen.AuxiliaryCellAttachment f s₀ x₀ γ) :=
  TopologicalSpace.coinduced
    (Quotient.mk (setoid f s₀ x₀ γ) :
      Prequotient f → Hatcher.VanKampen.AuxiliaryCellAttachment f s₀ x₀ γ)
    inferInstance

/-- The defining quotient map. -/
def quotientMk : Prequotient f →
    Hatcher.VanKampen.AuxiliaryCellAttachment f s₀ x₀ γ :=
  Quotient.mk (setoid f s₀ x₀ γ)

/-- The defining map is a quotient map for the coproduct topology. -/
theorem isQuotientMap_quotientMk :
    IsQuotientMap (quotientMk f s₀ x₀ γ) :=
  isQuotientMap_quot_mk

/-- The indexed cone attachment inside the auxiliary space. -/
def attachment : C(Hatcher.VanKampen.IndexedConeAttachment f,
    Hatcher.VanKampen.AuxiliaryCellAttachment f s₀ x₀ γ) where
  toFun y := quotientMk f s₀ x₀ γ (Sum.inl y)
  continuous_toFun :=
    (isQuotientMap_quotientMk f s₀ x₀ γ).continuous.comp continuous_inl

/-- The original base space inside the auxiliary space. -/
def base : C(X, Hatcher.VanKampen.AuxiliaryCellAttachment f s₀ x₀ γ) :=
  (attachment f s₀ x₀ γ).comp
    ⟨IndexedConeAttachment.base f, IndexedConeAttachment.continuous_base f⟩

/-- The apex of the cell indexed by `j`, viewed in the auxiliary space. -/
def apex (j : J) : Hatcher.VanKampen.AuxiliaryCellAttachment f s₀ x₀ γ :=
  attachment f s₀ x₀ γ (IndexedConeAttachment.apex f j)

/-- The common interval spine. Its zero endpoint is attached at `x₀`. -/
def spine : C(I, Hatcher.VanKampen.AuxiliaryCellAttachment f s₀ x₀ γ) where
  toFun t := quotientMk f s₀ x₀ γ (Sum.inr (Sum.inl t))
  continuous_toFun :=
    (isQuotientMap_quotientMk f s₀ x₀ γ).continuous.comp
      (continuous_inr.comp continuous_inl)

/-- The square strip belonging to the cell `j`. -/
def strip (j : J) :
    C(I × I, Hatcher.VanKampen.AuxiliaryCellAttachment f s₀ x₀ γ) where
  toFun p := quotientMk f s₀ x₀ γ (Sum.inr (Sum.inr ⟨j, p⟩))
  continuous_toFun := by
    have hsigma : Continuous (fun p : I × I ↦
        (⟨j, p⟩ : Sigma (fun _j : J ↦ I × I))) :=
      @continuous_sigmaMk J (fun _j : J ↦ I × I) (fun _ ↦ inferInstance) j
    exact (isQuotientMap_quotientMk f s₀ x₀ γ).continuous.comp
      (continuous_inr.comp (continuous_inr.comp hsigma))

/-- The indexed attachment and direct base maps agree on the original space. -/
@[simp] theorem attachment_base (x : X) :
    attachment f s₀ x₀ γ (IndexedConeAttachment.base f x) =
      base f s₀ x₀ γ x :=
  rfl

/-- The indexed attachment embeds as a set in the strip enlargement. -/
theorem attachment_injective : Function.Injective (attachment f s₀ x₀ γ) := by
  intro a b h
  have hrel := Quotient.exact h
  change normalForm f s₀ x₀ γ (Sum.inl a) =
    normalForm f s₀ x₀ γ (Sum.inl b) at hrel
  exact Sum.inl.inj hrel

/-- The common spine starts at the chosen basepoint. -/
@[simp] theorem spine_zero :
    spine f s₀ x₀ γ 0 = base f s₀ x₀ γ x₀ := by
  apply Quotient.sound
  change normalForm f s₀ x₀ γ (Sum.inr (Sum.inl 0)) =
    normalForm f s₀ x₀ γ
      (Sum.inl (IndexedConeAttachment.base f x₀))
  simp [normalForm]

/-- A strip's bottom edge follows its chosen basepoint path. -/
@[simp] theorem strip_bottom (j : J) (a : I) :
    strip f s₀ x₀ γ j (a, 0) = base f s₀ x₀ γ (γ j a) := by
  apply Quotient.sound
  change normalForm f s₀ x₀ γ (Sum.inr (Sum.inr ⟨j, (a, (0 : I))⟩)) =
    normalForm f s₀ x₀ γ
      (Sum.inl (IndexedConeAttachment.base f (γ j a)))
  simp [normalForm]

/-- Every strip's left edge is the common spine. -/
@[simp] theorem strip_left (j : J) (t : I) :
    strip f s₀ x₀ γ j (0, t) = spine f s₀ x₀ γ t := by
  apply Quotient.sound
  change normalForm f s₀ x₀ γ (Sum.inr (Sum.inr ⟨j, ((0 : I), t)⟩)) =
    normalForm f s₀ x₀ γ (Sum.inr (Sum.inl t))
  by_cases ht : t = 0
  · subst t
    simp [normalForm, (γ j).source]
  · simp [normalForm, ht]

/-- A strip's right edge follows a radial segment in its attached cone. -/
@[simp] theorem strip_right (j : J) (t : I) :
    strip f s₀ x₀ γ j (1, t) =
      attachment f s₀ x₀ γ
        (IndexedConeAttachment.cylinder
          f j (s₀ j) (truncatedRadialHeight t)) := by
  apply Quotient.sound
  change normalForm f s₀ x₀ γ (Sum.inr (Sum.inr ⟨j, ((1 : I), t)⟩)) =
    normalForm f s₀ x₀ γ
      (Sum.inl (IndexedConeAttachment.cylinder
        f j (s₀ j) (truncatedRadialHeight t)))
  by_cases ht : t = 0
  · subst t
    simp [normalForm, (γ j).target]
  · simp [normalForm, ht]

omit [TopologicalSpace X] [∀ j, TopologicalSpace (S j)] in
private theorem indexedCylinder_ne_apex (j k : J) (s : S j) (t : I)
    (ht : t ≠ 0) :
    IndexedConeAttachment.cylinder f j s t ≠ IndexedConeAttachment.apex f k := by
  intro h
  have hrel := Quotient.exact h
  change (if t = 0 then
      (Sum.inr ⟨j, Sum.inl ()⟩ : IndexedConeAttachment.Prequotient X S)
    else if t = 1 then Sum.inl (f j s)
    else Sum.inr ⟨j, Sum.inr (s, t)⟩) =
      Sum.inr ⟨k, Sum.inl ()⟩ at hrel
  by_cases h1 : t = 1
  · subst t
    simp at hrel
  · have htag := congrArg
      (fun z : IndexedConeAttachment.Prequotient X S =>
        match z with
        | Sum.inr ⟨_, Sum.inl _⟩ => true
        | _ => false)
      hrel
    simp [ht, h1] at htag

/-- A strip's radial edge misses every cone apex, including those of other
cells. -/
theorem strip_right_ne_apex (j k : J) (t : I) :
    strip f s₀ x₀ γ j (1, t) ≠ apex f s₀ x₀ γ k := by
  rw [strip_right]
  intro h
  exact indexedCylinder_ne_apex f j k (s₀ j) (truncatedRadialHeight t)
    (truncatedRadialHeight_ne_zero t)
    (attachment_injective f s₀ x₀ γ h)

end AuxiliaryCellAttachment

end Hatcher.VanKampen
