import Hatcher.VanKampen.AuxiliaryCellAttachmentAttachingMap
import Hatcher.VanKampen.CellAttachmentAlgebra
import Hatcher.VanKampen.CellAttachmentEmpty
import Hatcher.VanKampen.CellAttachmentIntersectionSurjective

/-!
# Fundamental groups after attaching two-cells

This file proves Hatcher's Proposition 1.26(a).  The attaching loops are
based at a common point by explicit paths, and their normal closure is shown
to be the kernel of the map induced by the attachment.  In particular, that
normal subgroup is independent of the chosen paths.
-/

noncomputable section

open CategoryTheory FundamentalGroupoid HomotopicalAlgebra Set Topology
open scoped ContinuousMap TopCat

namespace Hatcher

universe u v w

namespace VanKampen

/-- The attaching loop of the `i`-th two-cell, transported to the common
basepoint along the chosen path. -/
noncomputable def twoCellAttachingLoop
    {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint))
    (i : c.ι) : FundamentalGroup X x₀ :=
  (FundamentalGroup.fundamentalGroupMulEquivOfPath (γ i)).symm
    (FundamentalGroup.map
      (⟨CellAttachmentCover.attachingFamily c i,
        CellAttachment.continuous_attachingMap c i⟩ :
        C(CellAttachmentCover.Boundary.{u} 2, X))
      Hatcher.diskBoundaryTwoBasepoint
      AuxiliaryCellAttachment.diskBoundaryTwoGenerator)

/-- The normal subgroup generated by the transported attaching loops of a
family of two-cells. -/
def twoCellAttachingNormalSubgroup
    {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint)) :
    Subgroup (FundamentalGroup X x₀) :=
  Subgroup.normalClosure (Set.range (twoCellAttachingLoop c x₀ γ))

instance twoCellAttachingNormalSubgroup_normal
    {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint)) :
    (twoCellAttachingNormalSubgroup c x₀ γ).Normal := by
  unfold twoCellAttachingNormalSubgroup
  infer_instance

private abbrev twoCellBinaryCover
    {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint)) :=
  CellAttachmentCover.binaryCover c x₀
    Hatcher.diskBoundaryTwoBasepoint γ

private abbrev twoCellOverlapPieceCover
    {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint)) :=
  CellAttachmentCover.overlapPiece c x₀
    Hatcher.diskBoundaryTwoBasepoint γ

private abbrev twoCellOverlapBasepoint
    {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint)) :=
  AuxiliaryCellAttachment.overlapBasepoint
    (CellAttachmentCover.attachingFamily c)
    (CellAttachmentCover.boundaryPointFamily c
      Hatcher.diskBoundaryTwoBasepoint) x₀ γ

private abbrev twoCellIntersectionBasepoint
    {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint)) :=
  AuxiliaryCellAttachment.coverIntersectionBasepoint
    (CellAttachmentCover.attachingFamily c)
    (CellAttachmentCover.boundaryPointFamily c
      Hatcher.diskBoundaryTwoBasepoint) x₀ γ

private noncomputable def twoCellCover
    {X Y : TopCat.{u}} {f : X ⟶ Y} [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    [Nonempty c.ι] (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint)) :
    CellAttachmentCover c x₀ Hatcher.diskBoundaryTwoBasepoint γ :=
  Nonempty.some (exists_cellAttachmentCover c (by omega) x₀
    Hatcher.diskBoundaryTwoBasepoint γ)

set_option backward.isDefEq.respectTransparency false in
private abbrev twoCellOverlapRelationSubgroup
    {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint))
    (cover : CellAttachmentCover c x₀
      Hatcher.diskBoundaryTwoBasepoint γ) :
    Subgroup
      (CoverGroup (twoCellBinaryCover c x₀ γ)
        (twoCellOverlapBasepoint c x₀ γ)
        cover.overlapBasepointMem 0) :=
  Subgroup.normalClosure
    ((overlapToLeft (twoCellBinaryCover c x₀ γ)
      (twoCellOverlapBasepoint c x₀ γ)
      cover.overlapBasepointMem 0 1).range : Set _)

private instance twoCellOverlapRelationSubgroup_normal
    {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint))
    (cover : CellAttachmentCover c x₀
      Hatcher.diskBoundaryTwoBasepoint γ) :
    (twoCellOverlapRelationSubgroup c x₀ γ cover).Normal := by
  unfold twoCellOverlapRelationSubgroup
  infer_instance

private abbrev twoCellBaseFundamentalGroupEquiv
    {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint)) :=
  AuxiliaryCellAttachment.baseCoverFundamentalGroupEquiv
    (CellAttachmentCover.attachingFamily c)
    (CellAttachmentCover.boundaryPointFamily c
      Hatcher.diskBoundaryTwoBasepoint) x₀ γ
    (CellAttachment.continuous_attachingMap c)

set_option backward.isDefEq.respectTransparency false in
/-- Including one member of the overlap-piece cover into the binary
intersection and then into the base-side cover is the canonical direct
inclusion of that piece into the base-side cover. -/
private theorem overlapPieceCoverMap_to_baseCover
    {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint))
    (cover : CellAttachmentCover c x₀
      Hatcher.diskBoundaryTwoBasepoint γ)
    (i : c.ι)
    (g : CoverGroup (twoCellOverlapPieceCover c x₀ γ)
      (twoCellIntersectionBasepoint c x₀ γ)
      (AuxiliaryCellAttachment.coverIntersectionBasepoint_mem_intersectionPiece
        (CellAttachmentCover.attachingFamily c)
        (CellAttachmentCover.boundaryPointFamily c
          Hatcher.diskBoundaryTwoBasepoint) x₀ γ) i) :
    overlapToLeft (twoCellBinaryCover c x₀ γ)
        (twoCellOverlapBasepoint c x₀ γ)
        cover.overlapBasepointMem 0 1
        (coverMap (twoCellOverlapPieceCover c x₀ γ)
          (twoCellIntersectionBasepoint c x₀ γ)
          (AuxiliaryCellAttachment.coverIntersectionBasepoint_mem_intersectionPiece
            (CellAttachmentCover.attachingFamily c)
            (CellAttachmentCover.boundaryPointFamily c
              Hatcher.diskBoundaryTwoBasepoint) x₀ γ)
          (Monoid.CoprodI.of g)) =
      FundamentalGroup.mapOfEq
        (AuxiliaryCellAttachment.intersectionPieceToBaseCover
          (CellAttachmentCover.attachingFamily c)
          (CellAttachmentCover.boundaryPointFamily c
            Hatcher.diskBoundaryTwoBasepoint) x₀ γ i)
        (AuxiliaryCellAttachment.intersectionPieceToBaseCover_basepoint
          (CellAttachmentCover.attachingFamily c)
          (CellAttachmentCover.boundaryPointFamily c
            Hatcher.diskBoundaryTwoBasepoint) x₀ γ i) g := by
  simp only [coverMap, Monoid.CoprodI.lift_of, overlapToLeft]
  induction g using Path.Homotopic.Quotient.ind with
  | mk p =>
      change _ = FundamentalGroup.mapOfEq
        (AuxiliaryCellAttachment.intersectionPieceToBaseCover
          (CellAttachmentCover.attachingFamily c)
          (fun _ : c.ι ↦ Hatcher.diskBoundaryTwoBasepoint) x₀ γ i)
        (AuxiliaryCellAttachment.intersectionPieceToBaseCover_basepoint
          (CellAttachmentCover.attachingFamily c)
          (fun _ : c.ι ↦ Hatcher.diskBoundaryTwoBasepoint) x₀ γ i)
        (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk p))
      rw [FundamentalGroup.mapOfEq_apply]
      rfl

set_option backward.isDefEq.respectTransparency false in
private theorem twoCellOverlapRelationSubgroup_map_eq
    {X Y : TopCat.{u}} {f : X ⟶ Y} [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    [Nonempty c.ι] (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint))
    (cover : CellAttachmentCover c x₀
      Hatcher.diskBoundaryTwoBasepoint γ) :
    (twoCellOverlapRelationSubgroup c x₀ γ cover).map
        (twoCellBaseFundamentalGroupEquiv c x₀ γ).toMonoidHom =
      twoCellAttachingNormalSubgroup c x₀ γ := by
  let F := CellAttachmentCover.attachingFamily c
  let s₀ := CellAttachmentCover.boundaryPointFamily c
    Hatcher.diskBoundaryTwoBasepoint
  let U := twoCellBinaryCover c x₀ γ
  let V := twoCellOverlapPieceCover c x₀ γ
  let z₀ := twoCellOverlapBasepoint c x₀ γ
  let zI := twoCellIntersectionBasepoint c x₀ γ
  let hz₀ := cover.overlapBasepointMem
  let hzI := AuxiliaryCellAttachment.coverIntersectionBasepoint_mem_intersectionPiece
    F s₀ x₀ γ
  let L := overlapToLeft U z₀ hz₀ 0 1
  let E := twoCellBaseFundamentalGroupEquiv c x₀ γ
  let K := twoCellOverlapRelationSubgroup c x₀ γ cover
  let N := twoCellAttachingNormalSubgroup c x₀ γ
  let P : CoverFreeProduct V zI hzI →* FundamentalGroup X x₀ :=
    E.toMonoidHom.comp (L.comp (coverMap V zI hzI))
  letI : ((twoCellAttachingNormalSubgroup c x₀ γ).comap
      (twoCellBaseFundamentalGroupEquiv c x₀ γ).toMonoidHom).Normal :=
    Subgroup.Normal.comap
      (twoCellAttachingNormalSubgroup_normal c x₀ γ)
      (twoCellBaseFundamentalGroupEquiv c x₀ γ).toMonoidHom
  letI : (K.map E.toMonoidHom).Normal :=
    Subgroup.Normal.map (H := K) inferInstance E.toMonoidHom E.surjective
  have hmeridian : ∀ i : c.ι,
      P (Monoid.CoprodI.of
          (AuxiliaryCellAttachment.intersectionMeridian F x₀ γ i)) =
        twoCellAttachingLoop c x₀ γ i := by
    intro i
    change E (L (coverMap V zI hzI
      (Monoid.CoprodI.of
        (AuxiliaryCellAttachment.intersectionMeridian F x₀ γ i)))) = _
    rw [overlapPieceCoverMap_to_baseCover c x₀ γ cover i]
    exact AuxiliaryCellAttachment.intersectionMeridian_eq_attachingLoop
      F x₀ γ (CellAttachment.continuous_attachingMap c) i
  apply le_antisymm
  · rw [Subgroup.map_le_iff_le_comap]
    refine @Subgroup.normalClosure_le_normal _ _ _ _
      (Subgroup.Normal.comap
        (twoCellAttachingNormalSubgroup_normal c x₀ γ)
        (twoCellBaseFundamentalGroupEquiv c x₀ γ).toMonoidHom) ?_
    rintro b ⟨ω, rfl⟩
    change E (L ω) ∈ N
    obtain ⟨w, hw⟩ :=
      attachmentIntersection_coverMap_surjective c x₀
        Hatcher.diskBoundaryTwoBasepoint γ cover ω
    subst ω
    change P w ∈ N
    induction w using Monoid.CoprodI.induction_on with
    | one =>
        rw [map_one P]
        exact N.one_mem
    | of i g =>
        let O : CoverGroup V zI hzI i →* CoverFreeProduct V zI hzI :=
          Monoid.CoprodI.of
        let m := AuxiliaryCellAttachment.intersectionMeridian F x₀ γ i
        have hg : g ∈ Subgroup.zpowers m := by
          rw [AuxiliaryCellAttachment.intersectionMeridian_zpowers_eq_top]
          trivial
        obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp hg
        change P (O (m ^ n)) ∈ N
        have hO : O (m ^ n) = (O m) ^ n := O.map_zpow m n
        have hP : P ((O m) ^ n) = (P (O m)) ^ n := P.map_zpow (O m) n
        have hOm : P (O m) = twoCellAttachingLoop c x₀ γ i := by
          change P (Monoid.CoprodI.of
            (AuxiliaryCellAttachment.intersectionMeridian F x₀ γ i)) = _
          exact hmeridian i
        have hpow : P (O (m ^ n)) =
            (twoCellAttachingLoop c x₀ γ i) ^ n := by
          calc
            P (O (m ^ n)) = P ((O m) ^ n) := congrArg P hO
            _ = (P (O m)) ^ n := hP
            _ = (twoCellAttachingLoop c x₀ γ i) ^ n :=
              congrArg (fun x ↦ x ^ n) hOm
        exact hpow.symm ▸
          N.zpow_mem (Subgroup.subset_normalClosure ⟨i, rfl⟩) n
    | mul a b ha hb =>
        rw [map_mul P]
        exact N.mul_mem ha hb
  · apply Subgroup.normalClosure_le_normal
    rintro g ⟨i, rfl⟩
    let m := AuxiliaryCellAttachment.intersectionMeridian F x₀ γ i
    let ω := coverMap V zI hzI (Monoid.CoprodI.of m)
    refine ⟨L ω, ?_, ?_⟩
    · exact Subgroup.subset_normalClosure ⟨ω, rfl⟩
    · change P (Monoid.CoprodI.of m) = _
      exact hmeridian i

private theorem fundamentalGroup_map_pathChange
    {A : Type v} {B : Type w} [TopologicalSpace A] [TopologicalSpace B]
    (F : C(A, B)) {a b : A} (p : Path a b)
    (g : FundamentalGroup A a) :
    FundamentalGroup.map F b
        (FundamentalGroup.fundamentalGroupMulEquivOfPath p g) =
      FundamentalGroup.fundamentalGroupMulEquivOfPath
        (p.map F.continuous) (FundamentalGroup.map F a g) := by
  exact (FundamentalGroupoid.map F).map_conj
    ((Groupoid.isoEquivHom _ _).symm ⟦p⟧) g

set_option backward.isDefEq.respectTransparency false in
private noncomputable def twoCellAuxiliaryQuotientEquiv
    {X Y : TopCat.{u}} {f : X ⟶ Y} [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    [Nonempty c.ι] (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint))
    (cover : CellAttachmentCover c x₀
      Hatcher.diskBoundaryTwoBasepoint γ) :
    CoverGroup (twoCellBinaryCover c x₀ γ)
        (twoCellOverlapBasepoint c x₀ γ)
        cover.overlapBasepointMem 0 ⧸
      twoCellOverlapRelationSubgroup c x₀ γ cover ≃*
        FundamentalGroup Y (f x₀) := by
  let F := CellAttachmentCover.attachingFamily c
  let s₀ := CellAttachmentCover.boundaryPointFamily c
    Hatcher.diskBoundaryTwoBasepoint
  let U := twoCellBinaryCover c x₀ γ
  let z₀ := twoCellOverlapBasepoint c x₀ γ
  let hz₀ := cover.overlapBasepointMem
  let baseInclusion := AuxiliaryCellAttachment.baseCoverInclusion F s₀ x₀ γ
  let spinePath := AuxiliaryCellAttachment.basepointPath F s₀ x₀ γ
  let ambientSpinePath := spinePath.map baseInclusion.continuous
  letI : ContractibleSpace (U 1) := by
    change ContractibleSpace
      (CellAttachmentCover.upperCover c x₀
        Hatcher.diskBoundaryTwoBasepoint γ)
    exact cover.upperContractible
  let binaryEquiv := binaryCoverLeftQuotientEquivFundamentalGroupOfSubsingleton
    U z₀ cover.binaryCoverOpen cover.binaryCoverCovers
    cover.binaryCoverPathConnected cover.binaryIntersectionPathConnected hz₀
  let attachmentEquiv := cover.attachmentRetract.fundamentalGroupMulEquiv
    (IndexedConeAttachment.base F x₀)
  have hmodel :
      (TopCat.homeoOfIso cover.modelIso) (f x₀) =
        IndexedConeAttachment.base F x₀ := by
    exact ConcreteCategory.congr_hom cover.modelIso_base x₀
  let modelEquiv := fundamentalGroupMulEquivOfHomotopyEquivOfEq
    (TopCat.homeoOfIso cover.modelIso).toHomotopyEquiv
    (f x₀) (IndexedConeAttachment.base F x₀) hmodel
  exact binaryEquiv.trans
    (FundamentalGroup.fundamentalGroupMulEquivOfPath ambientSpinePath) |>.trans
    attachmentEquiv.symm |>.trans modelEquiv.symm

set_option backward.isDefEq.respectTransparency false in
private theorem twoCellAuxiliaryQuotientEquiv_mk
    {X Y : TopCat.{u}} {f : X ⟶ Y} [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    [Nonempty c.ι] (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint))
    (cover : CellAttachmentCover c x₀
      Hatcher.diskBoundaryTwoBasepoint γ)
    (g : CoverGroup (twoCellBinaryCover c x₀ γ)
      (twoCellOverlapBasepoint c x₀ γ)
      cover.overlapBasepointMem 0) :
    twoCellAuxiliaryQuotientEquiv c x₀ γ cover
        (QuotientGroup.mk'
          (twoCellOverlapRelationSubgroup c x₀ γ cover) g) =
      FundamentalGroup.map f.hom x₀
        (twoCellBaseFundamentalGroupEquiv c x₀ γ g) := by
  let F := CellAttachmentCover.attachingFamily c
  let s₀ := CellAttachmentCover.boundaryPointFamily c
    Hatcher.diskBoundaryTwoBasepoint
  let U := twoCellBinaryCover c x₀ γ
  let z₀ := twoCellOverlapBasepoint c x₀ γ
  let hz₀ := cover.overlapBasepointMem
  let E := twoCellBaseFundamentalGroupEquiv c x₀ γ
  let baseToBaseCover := AuxiliaryCellAttachment.baseToBaseCover F s₀ x₀ γ
  let baseInclusion := AuxiliaryCellAttachment.baseCoverInclusion F s₀ x₀ γ
  let spinePath := AuxiliaryCellAttachment.basepointPath F s₀ x₀ γ
  let ambientSpinePath := spinePath.map baseInclusion.continuous
  let attachment := AuxiliaryCellAttachment.attachment F s₀ x₀ γ
  let attachmentEquiv := cover.attachmentRetract.fundamentalGroupMulEquiv
    (IndexedConeAttachment.base F x₀)
  have hmodel :
      (TopCat.homeoOfIso cover.modelIso) (f x₀) =
        IndexedConeAttachment.base F x₀ := by
    exact ConcreteCategory.congr_hom cover.modelIso_base x₀
  let modelEquiv := fundamentalGroupMulEquivOfHomotopyEquivOfEq
    (TopCat.homeoOfIso cover.modelIso).toHomotopyEquiv
    (f x₀) (IndexedConeAttachment.base F x₀) hmodel
  letI : ContractibleSpace (U 1) := by
    change ContractibleSpace
      (CellAttachmentCover.upperCover c x₀
        Hatcher.diskBoundaryTwoBasepoint γ)
    exact cover.upperContractible
  have hbaseCover :
      FundamentalGroup.fundamentalGroupMulEquivOfPath ambientSpinePath
          (binaryCoverInclusion U z₀ hz₀ 0 g) =
        FundamentalGroup.map baseInclusion (baseToBaseCover x₀)
          (FundamentalGroup.map baseToBaseCover x₀ (E g)) := by
    have hg : g =
        (FundamentalGroup.fundamentalGroupMulEquivOfPath spinePath).symm
          (FundamentalGroup.map baseToBaseCover x₀ (E g)) := by
      calc
        g = E.symm (E g) := (E.symm_apply_apply g).symm
        _ = (FundamentalGroup.fundamentalGroupMulEquivOfPath spinePath).symm
            (FundamentalGroup.map baseToBaseCover x₀ (E g)) := by
          rw [AuxiliaryCellAttachment.baseCoverFundamentalGroupEquiv_symm_apply]
          rfl
    calc
      FundamentalGroup.fundamentalGroupMulEquivOfPath ambientSpinePath
          (binaryCoverInclusion U z₀ hz₀ 0 g) =
        FundamentalGroup.fundamentalGroupMulEquivOfPath ambientSpinePath
          (FundamentalGroup.map baseInclusion _
            ((FundamentalGroup.fundamentalGroupMulEquivOfPath spinePath).symm
              (FundamentalGroup.map baseToBaseCover x₀ (E g)))) := by
            nth_rewrite 1 [hg]
            rfl
      _ = FundamentalGroup.map baseInclusion (baseToBaseCover x₀)
          (FundamentalGroup.map baseToBaseCover x₀ (E g)) :=
        (fundamentalGroup_map_pathChange baseInclusion spinePath
          ((FundamentalGroup.fundamentalGroupMulEquivOfPath spinePath).symm
            (FundamentalGroup.map baseToBaseCover x₀ (E g)))).symm.trans
              (by simp)
  have hattachment :
      attachmentEquiv.symm
          (FundamentalGroup.map baseInclusion (baseToBaseCover x₀)
            (FundamentalGroup.map baseToBaseCover x₀ (E g))) =
        FundamentalGroup.map
          (IndexedConeAttachment.baseHom F).hom x₀ (E g) := by
    apply attachmentEquiv.injective
    rw [attachmentEquiv.apply_symm_apply]
    change
      FundamentalGroup.map baseInclusion (baseToBaseCover x₀)
          (FundamentalGroup.map baseToBaseCover x₀ (E g)) =
        FundamentalGroup.map attachment
          (IndexedConeAttachment.base F x₀)
          (FundamentalGroup.map
            (IndexedConeAttachment.baseHom F).hom x₀ (E g))
    induction E g using Path.Homotopic.Quotient.ind with
    | mk p => rfl
  have hmodelMap :
      modelEquiv.symm
          (FundamentalGroup.map
            (IndexedConeAttachment.baseHom F).hom x₀ (E g)) =
        FundamentalGroup.map f.hom x₀ (E g) := by
    apply modelEquiv.injective
    rw [modelEquiv.apply_symm_apply]
    rw [fundamentalGroupMulEquivOfHomotopyEquivOfEq_apply]
    induction E g using Path.Homotopic.Quotient.ind with
    | mk p =>
        rw [FundamentalGroup.map_apply, ← Path.Homotopic.Quotient.mk_map]
        rw [FundamentalGroup.map_apply, ← Path.Homotopic.Quotient.mk_map]
        rw [FundamentalGroup.mapOfEq_apply]
        apply congrArg FundamentalGroup.fromPath
        apply congrArg Path.Homotopic.Quotient.mk
        ext t
        exact (ConcreteCategory.congr_hom cover.modelIso_base (p t)).symm
  change modelEquiv.symm
      (attachmentEquiv.symm
        (FundamentalGroup.fundamentalGroupMulEquivOfPath ambientSpinePath
          (binaryCoverLeftQuotientEquivFundamentalGroupOfSubsingleton
            U z₀ cover.binaryCoverOpen cover.binaryCoverCovers
            cover.binaryCoverPathConnected cover.binaryIntersectionPathConnected hz₀
            (QuotientGroup.mk' _ g)))) = _
  rw [binaryCoverLeftQuotientEquivFundamentalGroupOfSubsingleton_mk,
    hbaseCover, hattachment, hmodelMap]

private theorem fundamentalGroup_map_attachTwoCells_surjective_of_nonempty
    {X Y : TopCat.{u}} {f : X ⟶ Y} [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    [Nonempty c.ι] (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint)) :
    Function.Surjective (FundamentalGroup.map f.hom x₀) := by
  let cover := twoCellCover c x₀ γ
  let E := twoCellBaseFundamentalGroupEquiv c x₀ γ
  let Q := twoCellAuxiliaryQuotientEquiv c x₀ γ cover
  intro y
  obtain ⟨q, rfl⟩ := Q.surjective y
  obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective
    (twoCellOverlapRelationSubgroup c x₀ γ cover) q
  refine ⟨E g, ?_⟩
  exact (twoCellAuxiliaryQuotientEquiv_mk c x₀ γ cover g).symm

set_option backward.isDefEq.respectTransparency false in
private theorem fundamentalGroup_map_attachTwoCells_ker_of_nonempty
    {X Y : TopCat.{u}} {f : X ⟶ Y} [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    [Nonempty c.ι] (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint)) :
    MonoidHom.ker (FundamentalGroup.map f.hom x₀) =
      twoCellAttachingNormalSubgroup c x₀ γ := by
  let cover := twoCellCover c x₀ γ
  let E := twoCellBaseFundamentalGroupEquiv c x₀ γ
  let K := twoCellOverlapRelationSubgroup c x₀ γ cover
  let N := twoCellAttachingNormalSubgroup c x₀ γ
  let Q := twoCellAuxiliaryQuotientEquiv c x₀ γ cover
  letI : (twoCellOverlapRelationSubgroup c x₀ γ cover).Normal :=
    twoCellOverlapRelationSubgroup_normal c x₀ γ cover
  have hKN : K.map E.toMonoidHom = N :=
    twoCellOverlapRelationSubgroup_map_eq c x₀ γ cover
  ext g
  constructor
  · intro hg
    have hmap : FundamentalGroup.map f.hom x₀ g = 1 :=
      MonoidHom.mem_ker.mp hg
    let b := E.symm g
    have hQ : Q (QuotientGroup.mk' K b) = 1 := by
      rw [twoCellAuxiliaryQuotientEquiv_mk]
      change FundamentalGroup.map f.hom x₀ (E (E.symm g)) = 1
      rw [E.apply_symm_apply]
      exact hmap
    have hmk : QuotientGroup.mk' K b = 1 :=
      Q.injective (hQ.trans (map_one Q).symm)
    have hb' : b ∈ twoCellOverlapRelationSubgroup c x₀ γ cover :=
      (@QuotientGroup.eq_one_iff _ _
        (twoCellOverlapRelationSubgroup c x₀ γ cover)
        (twoCellOverlapRelationSubgroup_normal c x₀ γ cover) b).mp hmk
    have hb : b ∈ K := hb'
    change g ∈ N
    have hg' : g ∈ K.map E.toMonoidHom :=
      ⟨b, hb, E.apply_symm_apply g⟩
    rw [hKN] at hg'
    exact hg'
  · intro hg
    change g ∈ N at hg
    have hg' : g ∈ K.map E.toMonoidHom := by
      rw [hKN]
      exact hg
    obtain ⟨b, hb, hbg⟩ := Subgroup.mem_map.mp hg'
    apply MonoidHom.mem_ker.mpr
    have hb' : b ∈ twoCellOverlapRelationSubgroup c x₀ γ cover := hb
    have hmk : QuotientGroup.mk' K b = 1 :=
      (@QuotientGroup.eq_one_iff _ _
        (twoCellOverlapRelationSubgroup c x₀ γ cover)
        (twoCellOverlapRelationSubgroup_normal c x₀ γ cover) b).mpr hb'
    have hQ := congrArg Q hmk
    rw [twoCellAuxiliaryQuotientEquiv_mk, map_one] at hQ
    rw [← hbg]
    exact hQ

private noncomputable def emptyTwoCellFundamentalGroupEquiv
    {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    [IsEmpty c.ι] (x₀ : X) :
    FundamentalGroup X x₀ ≃* FundamentalGroup Y (f x₀) :=
  fundamentalGroupMulEquivOfHomotopyEquiv
    (TopCat.homeoOfIso
      (CellAttachment.targetIsoOfIsEmpty c).symm).toHomotopyEquiv x₀

private theorem emptyTwoCellFundamentalGroupEquiv_apply
    {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    [IsEmpty c.ι] (x₀ : X) (g : FundamentalGroup X x₀) :
    emptyTwoCellFundamentalGroupEquiv c x₀ g =
      FundamentalGroup.map f.hom x₀ g := by
  have hmap :
      (TopCat.homeoOfIso
        (CellAttachment.targetIsoOfIsEmpty c).symm).toHomotopyEquiv.toFun =
          f.hom := by
    ext x
    change (CellAttachment.targetIsoOfIsEmpty c).inv x = f x
    rw [CellAttachment.targetIsoOfIsEmpty_inv]
  change FundamentalGroup.map
    (TopCat.homeoOfIso
      (CellAttachment.targetIsoOfIsEmpty c).symm).toHomotopyEquiv.toFun
      x₀ g = FundamentalGroup.map f.hom x₀ g
  cases hmap
  rfl

private theorem twoCellAttachingNormalSubgroup_eq_bot_of_isEmpty
    {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    [IsEmpty c.ι] (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        Hatcher.diskBoundaryTwoBasepoint)) :
    twoCellAttachingNormalSubgroup c x₀ γ = ⊥ := by
  apply le_antisymm
  · apply Subgroup.normalClosure_le_normal
    rintro g ⟨i, rfl⟩
    exact isEmptyElim i
  · exact bot_le

end VanKampen

/-- Attaching any family of two-cells to a path-connected space induces a
surjection on fundamental groups. -/
theorem fundamentalGroup_map_attachTwoCells_surjective
    {X Y : TopCat.{u}} {f : X ⟶ Y} [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X) :
    Function.Surjective (FundamentalGroup.map f.hom x₀) := by
  classical
  by_cases hι : Nonempty c.ι
  · letI := hι
    let γ : ∀ i : c.ι, Path x₀
        (VanKampen.CellAttachmentCover.attachingFamily c i
          diskBoundaryTwoBasepoint) :=
      fun i ↦ PathConnectedSpace.somePath _ _
    exact VanKampen.fundamentalGroup_map_attachTwoCells_surjective_of_nonempty
      c x₀ γ
  · letI : IsEmpty c.ι := ⟨fun i ↦ hι ⟨i⟩⟩
    intro g
    obtain ⟨h, rfl⟩ :=
      (VanKampen.emptyTwoCellFundamentalGroupEquiv c x₀).surjective g
    exact ⟨h,
      (VanKampen.emptyTwoCellFundamentalGroupEquiv_apply c x₀ h).symm⟩

/-- The kernel of the fundamental-group map induced by a two-cell attachment
is exactly the normal closure of the explicitly based attaching loops. -/
theorem fundamentalGroup_map_attachTwoCells_ker
    {X Y : TopCat.{u}} {f : X ⟶ Y} [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (VanKampen.CellAttachmentCover.attachingFamily c i
        diskBoundaryTwoBasepoint)) :
    MonoidHom.ker (FundamentalGroup.map f.hom x₀) =
      VanKampen.twoCellAttachingNormalSubgroup c x₀ γ := by
  classical
  by_cases hι : Nonempty c.ι
  · letI := hι
    exact VanKampen.fundamentalGroup_map_attachTwoCells_ker_of_nonempty
      c x₀ γ
  · letI : IsEmpty c.ι := ⟨fun i ↦ hι ⟨i⟩⟩
    rw [VanKampen.twoCellAttachingNormalSubgroup_eq_bot_of_isEmpty]
    apply (FundamentalGroup.map f.hom x₀).ker_eq_bot
    intro a b hab
    apply (VanKampen.emptyTwoCellFundamentalGroupEquiv c x₀).injective
    simpa only [VanKampen.emptyTwoCellFundamentalGroupEquiv_apply] using hab

/-- The normal subgroup generated by the transported attaching loops does not
depend on the paths used to transport their basepoints. -/
theorem twoCellAttachingNormalSubgroup_independent
    {X Y : TopCat.{u}} {f : X ⟶ Y} [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ δ : ∀ i : c.ι, Path x₀
      (VanKampen.CellAttachmentCover.attachingFamily c i
        diskBoundaryTwoBasepoint)) :
    VanKampen.twoCellAttachingNormalSubgroup c x₀ γ =
      VanKampen.twoCellAttachingNormalSubgroup c x₀ δ := by
  rw [← fundamentalGroup_map_attachTwoCells_ker c x₀ γ,
    ← fundamentalGroup_map_attachTwoCells_ker c x₀ δ]

/-- **Hatcher, Proposition 1.26(a) (page 50).** Attaching an arbitrary
family of two-cells quotients the fundamental group by the normal closure of
the transported attaching loops. -/
noncomputable def fundamentalGroup_quotient_of_attachTwoCells
    {X Y : TopCat.{u}} {f : X ⟶ Y} [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (VanKampen.CellAttachmentCover.attachingFamily c i
        diskBoundaryTwoBasepoint)) :
    FundamentalGroup X x₀ ⧸
        VanKampen.twoCellAttachingNormalSubgroup c x₀ γ ≃*
      FundamentalGroup Y (f x₀) :=
  (QuotientGroup.quotientMulEquivOfEq
    (fundamentalGroup_map_attachTwoCells_ker c x₀ γ).symm).trans
      (QuotientGroup.quotientKerEquivOfSurjective
        (FundamentalGroup.map f.hom x₀)
        (fundamentalGroup_map_attachTwoCells_surjective c x₀))

/-- The quotient equivalence is induced by the original attachment map. -/
@[simp]
theorem fundamentalGroup_quotient_of_attachTwoCells_mk
    {X Y : TopCat.{u}} {f : X ⟶ Y} [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} 2) f)
    (x₀ : X)
    (γ : ∀ i : c.ι, Path x₀
      (VanKampen.CellAttachmentCover.attachingFamily c i
        diskBoundaryTwoBasepoint))
    (g : FundamentalGroup X x₀) :
    fundamentalGroup_quotient_of_attachTwoCells c x₀ γ
        (QuotientGroup.mk'
          (VanKampen.twoCellAttachingNormalSubgroup c x₀ γ) g) =
      FundamentalGroup.map f.hom x₀ g := by
  rfl

end Hatcher
