import Hatcher.VanKampen.CellAttachmentCoverModel
import Hatcher.VanKampen.CoverMapSurjective

/-!
# The fundamental group of the attachment overlap is generated by its pieces

This file specializes the surjectivity clause of van Kampen's theorem to the
canonical cover of the overlap in Hatcher's auxiliary cell-attachment model.
-/

noncomputable section

open CategoryTheory HomotopicalAlgebra Set Topology
open scoped TopCat

namespace Hatcher.VanKampen

universe u

/-- The fundamental groups of the individual attaching-sphere pieces jointly
generate the fundamental group of the overlap in Hatcher's auxiliary cover. -/
theorem attachmentIntersection_coverMap_surjective
    {n : ℕ} {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} n) f)
    (x₀ : X) (s₀ : CellAttachmentCover.Boundary.{u} n)
    (gamma : ∀ i : c.ι,
      Path x₀ (CellAttachmentCover.attachingFamily c i s₀))
    (cover : CellAttachmentCover c x₀ s₀ gamma) :
    Function.Surjective
      (coverMap
        (CellAttachmentCover.overlapPiece c x₀ s₀ gamma)
        (AuxiliaryCellAttachment.coverIntersectionBasepoint
          (CellAttachmentCover.attachingFamily c)
          (CellAttachmentCover.boundaryPointFamily c s₀) x₀ gamma)
        (AuxiliaryCellAttachment.coverIntersectionBasepoint_mem_intersectionPiece
          (CellAttachmentCover.attachingFamily c)
          (CellAttachmentCover.boundaryPointFamily c s₀) x₀ gamma)) := by
  exact coverMap_surjective
    (CellAttachmentCover.overlapPiece c x₀ s₀ gamma)
    (AuxiliaryCellAttachment.coverIntersectionBasepoint
      (CellAttachmentCover.attachingFamily c)
      (CellAttachmentCover.boundaryPointFamily c s₀) x₀ gamma)
    cover.overlapOpenCover.1
    cover.overlapOpenCover.2.1
    cover.overlapOpenCover.2.2.1
    (AuxiliaryCellAttachment.coverIntersectionBasepoint_mem_intersectionPiece
      (CellAttachmentCover.attachingFamily c)
      (CellAttachmentCover.boundaryPointFamily c s₀) x₀ gamma)

end Hatcher.VanKampen
