import Hatcher.Sphere.SimplyConnected
import Hatcher.VanKampen.CellAttachmentAlgebra
import Hatcher.VanKampen.CellAttachmentEmpty
import Hatcher.VanKampen.CellAttachmentIntersectionSurjective

/-!
# Fundamental groups after attaching higher-dimensional cells

This file proves Hatcher's Proposition 1.26(b): attaching cells of a fixed
dimension greater than two does not change the fundamental group.  The proof
uses the strip-enlarged binary cover, whose upper member is contractible and
whose overlap is generated by pieces homotopy equivalent to the attaching
spheres.
-/

noncomputable section

open CategoryTheory FundamentalGroupoid HomotopicalAlgebra Set Topology
open scoped ContinuousMap TopCat

namespace Hatcher

universe u v w

namespace VanKampen

private theorem simplyConnectedSpace_cellAttachmentBoundary
    {n : ℕ} (hn : 2 < n) :
    SimplyConnectedSpace (CellAttachmentCover.Boundary.{u} n) := by
  obtain ⟨k, hk⟩ : ∃ k, n = k + 3 := ⟨n - 3, by omega⟩
  subst n
  letI : SimplyConnectedSpace
      (Metric.sphere (0 : EuclideanSpace ℝ (Fin (k + 3))) 1) := by
    simpa [Nat.add_assoc] using Sphere.simplyConnectedSpace k
  change SimplyConnectedSpace
    (ULift.{u} (Metric.sphere (0 : EuclideanSpace ℝ (Fin (k + 3))) 1))
  exact Homeomorph.ulift.toHomotopyEquiv.simplyConnectedSpace

private theorem coprodISubsingleton
    {ι : Type u} {G : ι → Type v} [∀ i, Group (G i)]
    [∀ i, Subsingleton (G i)] : Subsingleton (Monoid.CoprodI G) := by
  refine ⟨fun a b ↦ ?_⟩
  have hOne : ∀ x : Monoid.CoprodI G, x = 1 := by
    intro x
    induction x using Monoid.CoprodI.induction_on with
    | one => rfl
    | of i g =>
        rw [show g = 1 from Subsingleton.elim g 1]
        exact map_one _
    | mul a b ha hb => simp [ha, hb]
  exact (hOne a).trans (hOne b).symm

private theorem fundamentalGroup_map_pathChange
    {A : Type v} {B : Type w} [TopologicalSpace A] [TopologicalSpace B]
    (F : C(A, B)) {a b : A} (p : Path a b) (g : FundamentalGroup A a) :
    FundamentalGroup.map F b
        (FundamentalGroup.fundamentalGroupMulEquivOfPath p g) =
      FundamentalGroup.fundamentalGroupMulEquivOfPath
        (p.map F.continuous) (FundamentalGroup.map F a g) := by
  exact (FundamentalGroupoid.map F).map_conj
    ((Groupoid.isoEquivHom _ _).symm ⟦p⟧) g

private theorem simplyConnectedSpace_attachmentOverlap
    {n : ℕ} {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} n) f)
    [Nonempty c.ι] (hn : 2 < n) (x₀ : X)
    (s₀ : CellAttachmentCover.Boundary.{u} n)
    (gamma : ∀ i : c.ι,
      Path x₀ (CellAttachmentCover.attachingFamily c i s₀))
    (cover : CellAttachmentCover c x₀ s₀ gamma) :
    SimplyConnectedSpace (CellAttachmentCover.Overlap c x₀ s₀ gamma) := by
  letI : SimplyConnectedSpace (CellAttachmentCover.Boundary.{u} n) :=
    simplyConnectedSpace_cellAttachmentBoundary hn
  let U := CellAttachmentCover.overlapPiece c x₀ s₀ gamma
  let z₀ := AuxiliaryCellAttachment.coverIntersectionBasepoint
    (CellAttachmentCover.attachingFamily c)
    (CellAttachmentCover.boundaryPointFamily c s₀) x₀ gamma
  let hz₀ :=
    AuxiliaryCellAttachment.coverIntersectionBasepoint_mem_intersectionPiece
      (CellAttachmentCover.attachingFamily c)
      (CellAttachmentCover.boundaryPointFamily c s₀) x₀ gamma
  letI : ∀ i, Subsingleton (CoverGroup U z₀ hz₀ i) := fun i ↦ by
    letI : SimplyConnectedSpace (U i) :=
      (cover.overlapPieceEquiv i).simplyConnectedSpace
    infer_instance
  letI : Subsingleton (CoverFreeProduct U z₀ hz₀) :=
    coprodISubsingleton
  letI : Subsingleton
      (FundamentalGroup (CellAttachmentCover.Overlap c x₀ s₀ gamma) z₀) :=
    (attachmentIntersection_coverMap_surjective c x₀ s₀ gamma cover).subsingleton
  letI : PathConnectedSpace
      (CellAttachmentCover.Overlap c x₀ s₀ gamma) :=
    isPathConnected_iff_pathConnectedSpace.mp
      cover.binaryIntersectionPathConnected
  rw [simply_connected_iff_loops_nullhomotopic]
  refine ⟨inferInstance, fun x p ↦ ?_⟩
  let e := FundamentalGroup.fundamentalGroupMulEquivOfPathConnected z₀ x
  letI : Subsingleton
      (FundamentalGroup (CellAttachmentCover.Overlap c x₀ s₀ gamma) x) :=
    ⟨fun a b ↦ e.symm.injective (Subsingleton.elim (e.symm a) (e.symm b))⟩
  exact Path.Homotopic.Quotient.eq.mp
    (show
      (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk p) :
          FundamentalGroup (CellAttachmentCover.Overlap c x₀ s₀ gamma) x) =
        FundamentalGroup.fromPath
          (Path.Homotopic.Quotient.mk (Path.refl x))
      from Subsingleton.elim _ _)

private noncomputable def higherCellBoundaryPoint
    (n : ℕ) (hn : 2 < n) : CellAttachmentCover.Boundary.{u} n := by
  letI : SimplyConnectedSpace (CellAttachmentCover.Boundary.{u} n) :=
    simplyConnectedSpace_cellAttachmentBoundary hn
  exact Classical.choice (inferInstance : Nonempty
    (CellAttachmentCover.Boundary.{u} n))

private noncomputable def higherCellPathFamily
    {n : ℕ} {X Y : TopCat.{u}} {f : X ⟶ Y}
    [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} n) f)
    (hn : 2 < n) (x₀ : X) :
    ∀ i : c.ι, Path x₀
      (CellAttachmentCover.attachingFamily c i
        (higherCellBoundaryPoint n hn)) :=
  fun _ ↦ PathConnectedSpace.somePath _ _

private noncomputable def higherCellCover
    {n : ℕ} {X Y : TopCat.{u}} {f : X ⟶ Y}
    [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} n) f)
    [Nonempty c.ι] (hn : 2 < n) (x₀ : X) :
    CellAttachmentCover c x₀ (higherCellBoundaryPoint n hn)
      (higherCellPathFamily c hn x₀) :=
  Nonempty.some (exists_cellAttachmentCover c (by omega) x₀
    (higherCellBoundaryPoint n hn) (higherCellPathFamily c hn x₀))

private noncomputable def higherCellBinaryEquiv
    {n : ℕ} {X Y : TopCat.{u}} {f : X ⟶ Y}
    [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} n) f)
    [Nonempty c.ι] (hn : 2 < n) (x₀ : X) := by
  let s₀ := higherCellBoundaryPoint n hn
  let gamma := higherCellPathFamily c hn x₀
  let cover := higherCellCover c hn x₀
  let U := CellAttachmentCover.binaryCover c x₀ s₀ gamma
  let z₀ := AuxiliaryCellAttachment.overlapBasepoint
    (CellAttachmentCover.attachingFamily c)
    (CellAttachmentCover.boundaryPointFamily c s₀) x₀ gamma
  let hz₀ := cover.overlapBasepointMem
  letI : ContractibleSpace (U 1) := by
    change ContractibleSpace (CellAttachmentCover.upperCover c x₀ s₀ gamma)
    exact cover.upperContractible
  letI : SimplyConnectedSpace (U 0 ∩ U 1 : Set _) :=
    simplyConnectedSpace_attachmentOverlap c hn x₀ s₀ gamma cover
  letI : Subsingleton (OverlapGroup U z₀ hz₀ 0 1) := by
    infer_instance
  exact binaryCoverLeftEquivFundamentalGroupOfSimplyConnected U z₀
    cover.binaryCoverOpen cover.binaryCoverCovers
    cover.binaryCoverPathConnected cover.binaryIntersectionPathConnected hz₀

private theorem higherCellBinaryEquiv_apply
    {n : ℕ} {X Y : TopCat.{u}} {f : X ⟶ Y}
    [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} n) f)
    [Nonempty c.ι] (hn : 2 < n) (x₀ : X)
    (g : FundamentalGroup
      (CellAttachmentCover.baseCover c x₀ (higherCellBoundaryPoint n hn)
        (higherCellPathFamily c hn x₀))
      (AuxiliaryCellAttachment.baseCoverBasepoint
        (CellAttachmentCover.attachingFamily c)
        (CellAttachmentCover.boundaryPointFamily c
          (higherCellBoundaryPoint n hn)) x₀
        (higherCellPathFamily c hn x₀))) :
    higherCellBinaryEquiv c hn x₀ g =
      FundamentalGroup.map
        (AuxiliaryCellAttachment.baseCoverInclusion
          (CellAttachmentCover.attachingFamily c)
          (CellAttachmentCover.boundaryPointFamily c
            (higherCellBoundaryPoint n hn)) x₀
          (higherCellPathFamily c hn x₀)) _ g := by
  let s₀ := higherCellBoundaryPoint n hn
  let gamma := higherCellPathFamily c hn x₀
  let cover := higherCellCover c hn x₀
  let U := CellAttachmentCover.binaryCover c x₀ s₀ gamma
  let z₀ := AuxiliaryCellAttachment.overlapBasepoint
    (CellAttachmentCover.attachingFamily c)
    (CellAttachmentCover.boundaryPointFamily c s₀) x₀ gamma
  let hz₀ := cover.overlapBasepointMem
  letI : ContractibleSpace (U 1) := by
    change ContractibleSpace (CellAttachmentCover.upperCover c x₀ s₀ gamma)
    exact cover.upperContractible
  letI : SimplyConnectedSpace (U 0 ∩ U 1 : Set _) :=
    simplyConnectedSpace_attachmentOverlap c hn x₀ s₀ gamma cover
  letI : Subsingleton (OverlapGroup U z₀ hz₀ 0 1) := by
    infer_instance
  simp only [higherCellBinaryEquiv,
    binaryCoverLeftEquivFundamentalGroupOfSimplyConnected]
  exact binaryCoverLeftEquivFundamentalGroupOfSubsingleton_apply
    (CellAttachmentCover.binaryCover c x₀ (higherCellBoundaryPoint n hn)
      (higherCellPathFamily c hn x₀))
    (AuxiliaryCellAttachment.overlapBasepoint
      (CellAttachmentCover.attachingFamily c)
      (CellAttachmentCover.boundaryPointFamily c
        (higherCellBoundaryPoint n hn)) x₀
      (higherCellPathFamily c hn x₀))
    (higherCellCover c hn x₀).binaryCoverOpen
    (higherCellCover c hn x₀).binaryCoverCovers
    (higherCellCover c hn x₀).binaryCoverPathConnected
    (higherCellCover c hn x₀).binaryIntersectionPathConnected
    (higherCellCover c hn x₀).overlapBasepointMem g

private theorem baseFundamentalGroupEquiv_symm_apply
    {n : ℕ} {X Y : TopCat.{u}} {f : X ⟶ Y}
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} n) f)
    (x₀ : X) (s₀ : CellAttachmentCover.Boundary.{u} n)
    (gamma : ∀ i : c.ι,
      Path x₀ (CellAttachmentCover.attachingFamily c i s₀))
    (cover : CellAttachmentCover c x₀ s₀ gamma)
    (g : FundamentalGroup X x₀) :
    cover.baseFundamentalGroupEquiv.symm g =
      (FundamentalGroup.fundamentalGroupMulEquivOfPath
        cover.spinePath).symm
        (FundamentalGroup.map
          (AuxiliaryCellAttachment.baseToBaseCover
            (CellAttachmentCover.attachingFamily c)
            (CellAttachmentCover.boundaryPointFamily c s₀) x₀ gamma) x₀ g) := by
  apply cover.baseFundamentalGroupEquiv.injective
  rw [cover.baseFundamentalGroupEquiv.apply_symm_apply]
  let baseToBaseCover := AuxiliaryCellAttachment.baseToBaseCover
    (CellAttachmentCover.attachingFamily c)
    (CellAttachmentCover.boundaryPointFamily c s₀) x₀ gamma
  let w := (FundamentalGroup.fundamentalGroupMulEquivOfPath
    cover.spinePath).symm (FundamentalGroup.map baseToBaseCover x₀ g)
  change g = cover.baseFundamentalGroupEquiv.toMonoidHom w
  have hformula := DFunLike.congr_fun
    cover.baseFundamentalGroupEquiv_formula w
  calc
    g = FundamentalGroup.mapOfEq cover.baseCoverRetract.retract
        (cover.baseCoverRetract_base x₀)
        (FundamentalGroup.map baseToBaseCover x₀ g) := by
      symm
      induction g using Path.Homotopic.Quotient.ind with
      | mk p =>
          rw [FundamentalGroup.map_apply, ← Path.Homotopic.Quotient.mk_map]
          rw [FundamentalGroup.mapOfEq_apply]
          apply congrArg FundamentalGroup.fromPath
          apply congrArg Path.Homotopic.Quotient.mk
          ext t
          exact cover.baseCoverRetract_base (p t)
    _ = FundamentalGroup.mapOfEq cover.baseCoverRetract.retract
        (cover.baseCoverRetract_base x₀)
        (FundamentalGroup.fundamentalGroupMulEquivOfPath cover.spinePath w) := by
      rw [show FundamentalGroup.fundamentalGroupMulEquivOfPath
          cover.spinePath w = FundamentalGroup.map baseToBaseCover x₀ g by
        exact MulEquiv.apply_symm_apply _ _]
    _ = cover.baseFundamentalGroupEquiv.toMonoidHom w := hformula.symm

private noncomputable def higherCellEquivOfNonempty
    {n : ℕ} {X Y : TopCat.{u}} {f : X ⟶ Y}
    [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} n) f)
    [Nonempty c.ι] (hn : 2 < n) (x₀ : X) :
    FundamentalGroup X x₀ ≃* FundamentalGroup Y (f x₀) := by
  let s₀ := higherCellBoundaryPoint n hn
  let gamma := higherCellPathFamily c hn x₀
  let cover := higherCellCover c hn x₀
  let attachingFamily := CellAttachmentCover.attachingFamily c
  let boundaryPoints := CellAttachmentCover.boundaryPointFamily c s₀
  let baseInclusion := AuxiliaryCellAttachment.baseCoverInclusion
    attachingFamily boundaryPoints x₀ gamma
  let spinePath := cover.spinePath.map baseInclusion.continuous
  let attachmentEquiv := cover.attachmentRetract.fundamentalGroupMulEquiv
    (IndexedConeAttachment.base attachingFamily x₀)
  have hmodel :
      (TopCat.homeoOfIso cover.modelIso) (f x₀) =
        IndexedConeAttachment.base attachingFamily x₀ := by
    exact ConcreteCategory.congr_hom cover.modelIso_base x₀
  let modelEquiv := fundamentalGroupMulEquivOfHomotopyEquivOfEq
    (TopCat.homeoOfIso cover.modelIso).toHomotopyEquiv
    (f x₀) (IndexedConeAttachment.base attachingFamily x₀) hmodel
  exact cover.baseFundamentalGroupEquiv.symm |>.trans
    (higherCellBinaryEquiv c hn x₀) |>.trans
    (FundamentalGroup.fundamentalGroupMulEquivOfPath spinePath) |>.trans
    attachmentEquiv.symm |>.trans modelEquiv.symm

private theorem higherCellEquivOfNonempty_apply
    {n : ℕ} {X Y : TopCat.{u}} {f : X ⟶ Y}
    [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} n) f)
    [Nonempty c.ι] (hn : 2 < n) (x₀ : X)
    (g : FundamentalGroup X x₀) :
    higherCellEquivOfNonempty c hn x₀ g = FundamentalGroup.map f.hom x₀ g := by
  let s₀ := higherCellBoundaryPoint n hn
  let gamma := higherCellPathFamily c hn x₀
  let cover := higherCellCover c hn x₀
  let attachingFamily := CellAttachmentCover.attachingFamily c
  let boundaryPoints := CellAttachmentCover.boundaryPointFamily c s₀
  let baseToBaseCover := AuxiliaryCellAttachment.baseToBaseCover
    attachingFamily boundaryPoints x₀ gamma
  let baseInclusion := AuxiliaryCellAttachment.baseCoverInclusion
    attachingFamily boundaryPoints x₀ gamma
  let spinePath := cover.spinePath
  let ambientSpinePath := spinePath.map baseInclusion.continuous
  let attachment := AuxiliaryCellAttachment.attachment
    attachingFamily boundaryPoints x₀ gamma
  let attachmentEquiv := cover.attachmentRetract.fundamentalGroupMulEquiv
    (IndexedConeAttachment.base attachingFamily x₀)
  have hmodel :
      (TopCat.homeoOfIso cover.modelIso) (f x₀) =
        IndexedConeAttachment.base attachingFamily x₀ := by
    exact ConcreteCategory.congr_hom cover.modelIso_base x₀
  let modelEquiv := fundamentalGroupMulEquivOfHomotopyEquivOfEq
    (TopCat.homeoOfIso cover.modelIso).toHomotopyEquiv
    (f x₀) (IndexedConeAttachment.base attachingFamily x₀) hmodel
  have hbaseCover :
      FundamentalGroup.fundamentalGroupMulEquivOfPath ambientSpinePath
          (higherCellBinaryEquiv c hn x₀
            (cover.baseFundamentalGroupEquiv.symm g)) =
        FundamentalGroup.map baseInclusion (baseToBaseCover x₀)
          (FundamentalGroup.map baseToBaseCover x₀ g) := by
    rw [higherCellBinaryEquiv_apply,
      baseFundamentalGroupEquiv_symm_apply c x₀ s₀ gamma cover]
    exact (fundamentalGroup_map_pathChange baseInclusion spinePath
      ((FundamentalGroup.fundamentalGroupMulEquivOfPath spinePath).symm
        (FundamentalGroup.map baseToBaseCover x₀ g))).symm.trans (by simp)
  have hattachment :
      attachmentEquiv.symm
          (FundamentalGroup.map baseInclusion (baseToBaseCover x₀)
            (FundamentalGroup.map baseToBaseCover x₀ g)) =
        FundamentalGroup.map
          (IndexedConeAttachment.baseHom attachingFamily).hom x₀ g := by
    apply attachmentEquiv.injective
    rw [attachmentEquiv.apply_symm_apply]
    change
      FundamentalGroup.map baseInclusion (baseToBaseCover x₀)
          (FundamentalGroup.map baseToBaseCover x₀ g) =
        FundamentalGroup.map attachment
          (IndexedConeAttachment.base attachingFamily x₀)
          (FundamentalGroup.map
            (IndexedConeAttachment.baseHom attachingFamily).hom x₀ g)
    induction g using Path.Homotopic.Quotient.ind with
    | mk p => rfl
  have hmodelMap :
      modelEquiv.symm
          (FundamentalGroup.map
            (IndexedConeAttachment.baseHom attachingFamily).hom x₀ g) =
        FundamentalGroup.map f.hom x₀ g := by
    apply modelEquiv.injective
    rw [modelEquiv.apply_symm_apply]
    rw [fundamentalGroupMulEquivOfHomotopyEquivOfEq_apply]
    induction g using Path.Homotopic.Quotient.ind with
    | mk p =>
        rw [FundamentalGroup.map_apply, ← Path.Homotopic.Quotient.mk_map]
        rw [FundamentalGroup.map_apply, ← Path.Homotopic.Quotient.mk_map]
        rw [FundamentalGroup.mapOfEq_apply]
        apply congrArg FundamentalGroup.fromPath
        apply congrArg Path.Homotopic.Quotient.mk
        ext t
        exact (ConcreteCategory.congr_hom cover.modelIso_base (p t)).symm
  change modelEquiv.symm
      (attachmentEquiv.symm
        (FundamentalGroup.fundamentalGroupMulEquivOfPath ambientSpinePath
          (higherCellBinaryEquiv c hn x₀
            (cover.baseFundamentalGroupEquiv.symm g)))) = _
  rw [hbaseCover, hattachment, hmodelMap]

end VanKampen

/-- **Hatcher, Proposition 1.26(b) (pages 50--51).** If a path-connected
space is enlarged by attaching cells of one fixed dimension greater than two,
then the attachment map induces an equivalence on fundamental groups. -/
noncomputable def fundamentalGroupEquiv_of_attachCells_of_two_lt
    {n : ℕ} {X Y : TopCat.{u}} {f : X ⟶ Y}
    [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} n) f)
    (hn : 2 < n) (x₀ : X) :
    FundamentalGroup X x₀ ≃* FundamentalGroup Y (f x₀) := by
  classical
  by_cases hι : Nonempty c.ι
  · letI := hι
    exact VanKampen.higherCellEquivOfNonempty c hn x₀
  · letI : IsEmpty c.ι := ⟨fun i ↦ hι ⟨i⟩⟩
    exact fundamentalGroupMulEquivOfHomotopyEquiv
      (TopCat.homeoOfIso
        (VanKampen.CellAttachment.targetIsoOfIsEmpty c).symm).toHomotopyEquiv x₀

/-- The higher-cell equivalence is exactly the homomorphism induced by the
attachment map. -/
@[simp]
theorem fundamentalGroupEquiv_of_attachCells_of_two_lt_apply
    {n : ℕ} {X Y : TopCat.{u}} {f : X ⟶ Y}
    [PathConnectedSpace X]
    (c : AttachCells.{u} (TopCat.RelativeCWComplex.basicCell.{u} n) f)
    (hn : 2 < n) (x₀ : X) (g : FundamentalGroup X x₀) :
    fundamentalGroupEquiv_of_attachCells_of_two_lt c hn x₀ g =
      FundamentalGroup.map f.hom x₀ g := by
  classical
  by_cases hι : Nonempty c.ι
  · letI := hι
    rw [fundamentalGroupEquiv_of_attachCells_of_two_lt, dif_pos hι]
    exact VanKampen.higherCellEquivOfNonempty_apply c hn x₀ g
  · letI : IsEmpty c.ι := ⟨fun i ↦ hι ⟨i⟩⟩
    rw [fundamentalGroupEquiv_of_attachCells_of_two_lt, dif_neg hι]
    have hmap :
        (TopCat.homeoOfIso
          (VanKampen.CellAttachment.targetIsoOfIsEmpty c).symm).toHomotopyEquiv.toFun =
            f.hom := by
      ext x
      change (VanKampen.CellAttachment.targetIsoOfIsEmpty c).inv x = f x
      rw [VanKampen.CellAttachment.targetIsoOfIsEmpty_inv]
    change FundamentalGroup.map
      (TopCat.homeoOfIso
        (VanKampen.CellAttachment.targetIsoOfIsEmpty c).symm).toHomotopyEquiv.toFun
        x₀ g = FundamentalGroup.map f.hom x₀ g
    cases hmap
    rfl

end Hatcher
