import Mathlib.AlgebraicTopology.FundamentalGroupoid.FundamentalGroup
import Mathlib.GroupTheory.CoprodI

noncomputable section

namespace Hatcher.VanKampen

universe u v

variable {ι : Type u} {X : Type v} [TopologicalSpace X]

/-- The fundamental group of one member of a pointed cover. -/
abbrev CoverGroup (U : ι → Set X) (x₀ : X) (hx₀ : ∀ i, x₀ ∈ U i) (i : ι) :=
  FundamentalGroup (U i) (⟨x₀, hx₀ i⟩ : U i)

/-- The indexed free product of the fundamental groups of the cover members. -/
abbrev CoverFreeProduct (U : ι → Set X) (x₀ : X) (hx₀ : ∀ i, x₀ ∈ U i) :=
  Monoid.CoprodI (CoverGroup U x₀ hx₀)

/-- The fundamental group of a pairwise overlap in a pointed cover. -/
abbrev OverlapGroup (U : ι → Set X) (x₀ : X) (hx₀ : ∀ i, x₀ ∈ U i)
    (i j : ι) :=
  FundamentalGroup (U i ∩ U j : Set X)
    (⟨x₀, ⟨hx₀ i, hx₀ j⟩⟩ : (U i ∩ U j : Set X))

/-- The canonical homomorphism from the free product of the cover-member
fundamental groups to the fundamental group of the ambient space. -/
def coverMap (U : ι → Set X) (x₀ : X) (hx₀ : ∀ i, x₀ ∈ U i) :
    CoverFreeProduct U x₀ hx₀ →* FundamentalGroup X x₀ :=
  Monoid.CoprodI.lift fun i =>
    FundamentalGroup.map
      (⟨Subtype.val, continuous_subtype_val⟩ : C(U i, X))
      (⟨x₀, hx₀ i⟩ : U i)

/-- The map on fundamental groups from an overlap to its left cover member. -/
def overlapToLeft (U : ι → Set X) (x₀ : X) (hx₀ : ∀ i, x₀ ∈ U i)
    (i j : ι) : OverlapGroup U x₀ hx₀ i j →* CoverGroup U x₀ hx₀ i :=
  FundamentalGroup.map
    (⟨fun x => ⟨x.1, x.2.1⟩, continuous_subtype_val.subtype_mk _⟩ :
      C((U i ∩ U j : Set X), U i))
    (⟨x₀, ⟨hx₀ i, hx₀ j⟩⟩ : (U i ∩ U j : Set X))

/-- The map on fundamental groups from an overlap to its right cover member. -/
def overlapToRight (U : ι → Set X) (x₀ : X) (hx₀ : ∀ i, x₀ ∈ U i)
    (i j : ι) : OverlapGroup U x₀ hx₀ i j →* CoverGroup U x₀ hx₀ j :=
  FundamentalGroup.map
    (⟨fun x => ⟨x.1, x.2.2⟩, continuous_subtype_val.subtype_mk _⟩ :
      C((U i ∩ U j : Set X), U j))
    (⟨x₀, ⟨hx₀ i, hx₀ j⟩⟩ : (U i ∩ U j : Set X))

/-- The free-product relation identifying the two images of an overlap loop. -/
def overlapRelation (U : ι → Set X) (x₀ : X) (hx₀ : ∀ i, x₀ ∈ U i)
    (i j : ι) (ω : OverlapGroup U x₀ hx₀ i j) :
    CoverFreeProduct U x₀ hx₀ :=
  Monoid.CoprodI.of (overlapToLeft U x₀ hx₀ i j ω) *
    (Monoid.CoprodI.of (overlapToRight U x₀ hx₀ i j ω))⁻¹

/-- The set of relations contributed by all pairwise overlaps of the cover. -/
def overlapRelations (U : ι → Set X) (x₀ : X) (hx₀ : ∀ i, x₀ ∈ U i) :
    Set (CoverFreeProduct U x₀ hx₀) :=
  {r | ∃ (i j : ι) (ω : OverlapGroup U x₀ hx₀ i j),
    r = overlapRelation U x₀ hx₀ i j ω}

/-- The normal subgroup generated by the pairwise-overlap relations. -/
def relationSubgroup (U : ι → Set X) (x₀ : X) (hx₀ : ∀ i, x₀ ∈ U i) :
    Subgroup (CoverFreeProduct U x₀ hx₀) :=
  Subgroup.normalClosure (overlapRelations U x₀ hx₀)

end Hatcher.VanKampen
