/-
Hatcher, *Algebraic Topology*, Theorem 1.7 (page 29).

`π₁(S¹)` is infinite cyclic, generated by the class of `ω(s) = (cos 2πs, sin 2πs)`.

Both halves are Hatcher's, transcribed against Mathlib's covering-space API.

*Surjective.* The path `ω̃ₙ(s) = ns` in `ℝ` runs from `0` to `n` and projects to
the loop `ωₙ`. It is its own lift, so `ωₙ` has winding number `n`.

*Injective.* If two loops have the same winding number their lifts from `0`
share both endpoints, so they are homotopic in `ℝ`, which is contractible and
therefore simply connected. Projecting that homotopy back down identifies the
loops. The projection lands in `Path (expMap 0) (expMap c)` rather than
`Path 1 1`, so the last step transports along `expMap 0 = 1`, which holds
propositionally but not definitionally.
-/
import Hatcher.Circle.WindingNumber
import Mathlib.Analysis.Convex.Contractible
import Mathlib.GroupTheory.SpecificGroups.Cyclic

open Real unitInterval

namespace Hatcher.Circle

/-- Hatcher's `ωₙ(s) = (cos 2πns, sin 2πns)`, the loop of winding number `n`. -/
noncomputable def loopOfInt (n : ℤ) : Path (1 : _root_.Circle) 1 where
  toFun t := expMap ((n : ℝ) * t)
  continuous_toFun := by fun_prop
  source' := by simp
  target' := by simpa using expMap_intCast n

/-- Hatcher's `ω̃ₙ(s) = ns` is the lift of `ωₙ` starting at `0`. -/
theorem liftPath_loopOfInt (n : ℤ)
    (h : (loopOfInt n : C(I, _root_.Circle)) 0 = expMap (0 : ℝ)) :
    cov.liftPath (loopOfInt n) 0 h = ⟨fun t => (n : ℝ) * t, by fun_prop⟩ := by
  symm
  rw [cov.eq_liftPath_iff']
  refine ⟨funext fun t => rfl, ?_⟩
  show (n : ℝ) * ((0 : I) : ℝ) = 0
  simp

theorem monodromy_loopOfInt (n : ℤ) :
    ((cov.monodromy (Path.Homotopic.Quotient.mk (loopOfInt n) :
        Path.Homotopic.Quotient (1 : _root_.Circle) 1) fibreZero : Fibre) : ℝ) = (n : ℝ) := by
  have h := congr_arg (fun f : C(I, ℝ) => f 1) (liftPath_loopOfInt n (by simp))
  exact h.trans (by simp)

theorem windingNumberFun_loopOfInt (n : ℤ) :
    windingNumberFun (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk (loopOfInt n))) = n := by
  have h := cast_fibreToInt (cov.monodromy (Path.Homotopic.Quotient.mk (loopOfInt n) :
    Path.Homotopic.Quotient (1 : _root_.Circle) 1) fibreZero)
  rw [monodromy_loopOfInt n] at h
  exact_mod_cast h

theorem windingNumberFun_surjective : Function.Surjective windingNumberFun :=
  fun n => ⟨FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk (loopOfInt n)),
    windingNumberFun_loopOfInt n⟩

/-- Two loop classes with equal winding number are equal. -/
theorem windingNumberFun_injective : Function.Injective windingNumberFun := by
  intro γ δ h
  induction γ using Quotient.inductionOn with
  | h g =>
    induction δ using Quotient.inductionOn with
    | h d =>
      have hg : (g : C(I, _root_.Circle)) 0 = expMap (0 : ℝ) := g.source.trans expMap_zero.symm
      have hd : (d : C(I, _root_.Circle)) 0 = expMap (0 : ℝ) := d.source.trans expMap_zero.symm
      have hmono : ((cov.monodromy (Path.Homotopic.Quotient.mk g :
              Path.Homotopic.Quotient (1 : _root_.Circle) 1) fibreZero : Fibre) : ℝ)
          = ((cov.monodromy (Path.Homotopic.Quotient.mk d :
              Path.Homotopic.Quotient (1 : _root_.Circle) 1) fibreZero : Fibre) : ℝ) := by
        rw [← cast_fibreToInt, ← cast_fibreToInt]
        exact_mod_cast congr_arg (fun m : ℤ => (m : ℝ)) h
      have hend : (cov.liftPath (g : C(I, _root_.Circle)) 0 hg) 1
          = (cov.liftPath (d : C(I, _root_.Circle)) 0 hd) 1 := hmono
      set c : ℝ := (cov.liftPath (g : C(I, _root_.Circle)) 0 hg) 1 with hc
      have hglifts : ∀ t, expMap ((cov.liftPath (g : C(I, _root_.Circle)) 0 hg) t) = g t :=
        fun t => congr_fun (cov.liftPath_lifts
          (γ := (g : C(I, _root_.Circle))) (e := 0) (γ_0 := hg)) t
      have hdlifts : ∀ t, expMap ((cov.liftPath (d : C(I, _root_.Circle)) 0 hd) t) = d t :=
        fun t => congr_fun (cov.liftPath_lifts
          (γ := (d : C(I, _root_.Circle))) (e := 0) (γ_0 := hd)) t
      have hcirc : expMap c = 1 := (hglifts 1).trans g.target
      -- the two lifts, as paths in ℝ from 0 to c
      let Lg : Path (0 : ℝ) c :=
        ⟨cov.liftPath (g : C(I, _root_.Circle)) 0 hg, cov.liftPath_zero _ _ _, rfl⟩
      let Ld : Path (0 : ℝ) c :=
        ⟨cov.liftPath (d : C(I, _root_.Circle)) 0 hd, cov.liftPath_zero _ _ _, hend.symm⟩
      -- ℝ is contractible, hence simply connected: the lifts are homotopic
      have hlift : (Path.Homotopic.Quotient.mk Lg : Path.Homotopic.Quotient (0 : ℝ) c)
          = Path.Homotopic.Quotient.mk Ld := Subsingleton.elim _ _
      have hmap : Path.Homotopic.Quotient.mk (Lg.map cov.continuous)
          = Path.Homotopic.Quotient.mk (Ld.map cov.continuous) := by
        rw [Path.Homotopic.Quotient.mk_map, Path.Homotopic.Quotient.mk_map, hlift]
      -- transport along expMap 0 = 1 and expMap c = 1
      have hgc : g = (Lg.map cov.continuous).cast expMap_zero.symm hcirc.symm :=
        DFunLike.ext _ _ fun t => by
          rw [show (((Lg.map cov.continuous).cast expMap_zero.symm hcirc.symm) t)
            = (Lg.map cov.continuous) t from congr_fun (Path.cast_coe _ _ _) t]
          exact (hglifts t).symm
      have hdc : d = (Ld.map cov.continuous).cast expMap_zero.symm hcirc.symm :=
        DFunLike.ext _ _ fun t => by
          rw [show (((Ld.map cov.continuous).cast expMap_zero.symm hcirc.symm) t)
            = (Ld.map cov.continuous) t from congr_fun (Path.cast_coe _ _ _) t]
          exact (hdlifts t).symm
      rw [hgc, hdc]
      show (Path.Homotopic.Quotient.mk (Lg.map cov.continuous)).cast _ _
        = (Path.Homotopic.Quotient.mk (Ld.map cov.continuous)).cast _ _
      rw [hmap]

theorem windingNumber_bijective : Function.Bijective windingNumber :=
  ⟨fun a b h => windingNumberFun_injective (by simpa using h),
   fun n => ⟨FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk
      (loopOfInt (Multiplicative.toAdd n))), by
     show Multiplicative.ofAdd (windingNumberFun _) = n
     rw [windingNumberFun_loopOfInt]
     simp⟩⟩

/-- **Hatcher, Theorem 1.7 (page 29).** `π₁(S¹)` is infinite cyclic: the winding
number is an isomorphism `π₁(S¹) ≅ ℤ`. -/
noncomputable def fundamentalGroupEquivInt :
    FundamentalGroup _root_.Circle 1 ≃* Multiplicative ℤ :=
  MulEquiv.ofBijective windingNumber windingNumber_bijective

@[simp]
theorem fundamentalGroupEquivInt_apply (γ : FundamentalGroup _root_.Circle 1) :
    fundamentalGroupEquivInt γ = Multiplicative.ofAdd (windingNumberFun γ) := rfl

/-- Hatcher's generator `ω` has winding number one. -/
theorem windingNumberFun_loopOfInt_one :
    windingNumberFun (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk (loopOfInt 1))) = 1 :=
  windingNumberFun_loopOfInt 1

/-- `π₁(S¹)` is infinite. -/
theorem infinite_fundamentalGroup : Infinite (FundamentalGroup _root_.Circle 1) :=
  Infinite.of_injective _ fundamentalGroupEquivInt.symm.injective

/-- **Hatcher, Theorem 1.7 (page 29).** `π₁(S¹)` is an infinite cyclic group.

The generator is the class of `ω(s) = (cos 2πs, sin 2πs)`; see
`windingNumberFun_loopOfInt_one`, and `fundamentalGroupEquivInt` for the
isomorphism onto `ℤ` that witnesses this. -/
theorem isCyclic_fundamentalGroup : IsCyclic (FundamentalGroup _root_.Circle 1) :=
  isCyclic_of_surjective _ fundamentalGroupEquivInt.symm.surjective

end Hatcher.Circle
